#+PROPERTY: header-args :tangle "./.org-mode-contribute.emacs.el" :results output silent
#+OPTIONS: toc:3

Never compile this.

#+NAME: org_gcr_2017-07-21_mara_CC0CF0E1-0C39-4937-AD52-FBA49CA10E65
#+BEGIN_SRC emacs-lisp :comments no
;; -*- no-byte-compile: t; -*-
#+END_SRC

* Contribute
   :PROPERTIES:
   :ID:       org_gcr_2017-05-12_mara:B6246A7A-5514-4478-BC3D-7768B05B08B8
   :END:

#+NAME: org_gcr_2017-07-21_mara_CC0CF0E1-0C39-4937-AD52-FBA49CA10E65
#+BEGIN_SRC emacs-lisp :comments no
;; -*- no-byte-compile: t; -*-
#+END_SRC

Sysop is likely to use this periodically.

Start EMACS with this command:

#+BEGIN_EXAMPLE
emacs --debug-init --no-init-file --no-splash --background-color white --foreground-color black --vertical-scroll-bars --eval '(switch-to-buffer "*Messages*")' --name O2B-TEST --title O2B-TEST --load ~/src/help/.org-mode-contribute.emacs.el
#+END_EXAMPLE

#+NAME: org_gcr_2017-05-12_mara_AD27B44D-A88A-421F-9418-EE1B9E1977D5
#+BEGIN_SRC emacs-lisp
(load-file "~/src/help/.org-mode-package-management.emacs.el")
#+END_SRC
* xml-rpc
:PROPERTIES:
:ID:       org_gcr_2017-12-16_mara:8490F7FD-9718-4ADD-8A84-56A8D6625C12
:END:
#+BEGIN_QUOTE
An elisp implementation of clientside XML-RPC
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_3989AFAA-23E6-4463-98E8-90F7ED269C1B
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/xml-rpc-el")
(require 'xml-rpc)
#+END_SRC
* metaweblog
:PROPERTIES:
:ID:       org_gcr_2017-12-16_mara:C3B0266C-F9EC-498B-ABBA-486090654DDA
:END:
#+BEGIN_QUOTE
Weblog maintenance via XML-RPC APIs
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_C057BFE2-7242-495D-BCD2-62C6389A6551
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/metaweblog")
(require 'metaweblog)
#+END_SRC
* Org2blog
:PROPERTIES:
:ID:       org_gcr_2018-03-03_mara:60113001-1991-4EB5-BF61-190C198AF742
:END:
Configure Org2blog for use, development, and support.
#+BEGIN_QUOTE
Blog from Org mode to wordpress
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_EF1B02DF-BDB7-44AA-A018-B0BE6DA1C08F
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/org2blog")
(require 'org2blog)
(add-hook 'org-mode-hook #'org2blog/wp-org-mode-hook-fn)
#+END_SRC

Use [[https://www.mathjax.org/][MathJax]] instead of =wp-latex= syntax.

#+NAME: org_gcr_2017-08-14_mara_7625680E-1CA4-428E-A92F-D53114742D28
#+BEGIN_SRC emacs-lisp
(setq org2blog/wp-use-wp-latex nil)
#+END_SRC

Org2Blog depends on Org-Mode. This system loads Org-Mode from Git. Enter the
=ELPA= cache directory and delete it.

This system works with WisdomAndWonder. It keeps its posts separate giving focus
to each Web.

#+NAME: org_gcr_2017-05-12_mara_FF96F4B6-42B9-45D6-BEE6-6CDC9D6815AE
#+BEGIN_SRC emacs-lisp
(setq org2blog/wp-track-posts nil)
#+END_SRC

Post creation handler.

#+NAME: org_gcr_2017-08-04_mara_B782FF06-D0E7-4598-89E4-02A76E882E78
#+BEGIN_SRC emacs-lisp
(add-hook 'org2blog/wp-after-new-post-or-page-functions (lambda (p) (pp p)))
#+END_SRC

Configure Org2Blog.

#+NAME: org_gcr_2017-05-12_mara_854DE6E9-2208-42EB-A164-EC06E489B6B7
#+BEGIN_SRC emacs-lisp
(require 'auth-source)
(let* ((credentials (auth-source-user-and-password "wisdomandwonder"))
       (username (nth 0 credentials))
       (password (nth 1 credentials))
       (config `(("wisdomandwonder"
                  :url "https://www.wisdomandwonder.com/xmlrpc.php"
                  :username ,username
                  :password ,password
                  :default-categories ("Happiness" "WisdomAndWonder")
                  :confirm t
                  :show 'show))))
  (setq org2blog/wp-blog-alist config))
#+END_SRC

* Pretty Mode
:PROPERTIES:
:ID:       org_gcr_2017-05-15_mara:CB452410-955E-4A91-A811-10755A35A142
:END:

Visualize ASCII values as their most likely Unicode representation.

#+NAME: org_gcr_2017-05-15_mara_5CF1DF19-27F5-4509-8E17-9CA0D1B29314
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/pretty-mode")
(require 'pretty-mode)
#+END_SRC
* go-hydra
:PROPERTIES:
:ID:       org_gcr_2017-08-01_mara:F1CA18C6-F00E-4F1A-BBD3-77FC52B437E8
:END:
A collection of Go related Hydras for Emacs.

#+NAME: org_gcr_2017-08-01_mara_A0E420CB-EBB0-4D31-BC97-8FE54008F93D
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/go-hydra")
(require 'go-hydra)
#+END_SRC
* universal-emotions-emoticons
:PROPERTIES:
:ID:       org_gcr_2017-12-05_mara:BAEA6BB3-614D-4957-BEFF-4AE9E6271BF1
:END:
#+NAME: org_gcr_2017-12-05_mara_62849D6E-BD7B-4289-AC2C-CF8B51B9C633
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/universal-emotions-emoticons")
(require 'universal-emotions-emoticons)
#+END_SRC
* corporate-bs-generator
:PROPERTIES:
:ID:       org_gcr_2018-07-06T22-26-05-05-00_mara:EBD3FC34-3153-4E01-A8DD-099CF51A08EF
:END:
#+name: org_gcr_2018-07-06T22-26-05-05-00_mara_8504E527-9CB6-4CF7-AF8D-5E98CCA540E6
#+begin_src emacs-lisp
(add-to-list 'load-path "~/src/corporate-bs-generator")
(require 'corporate-bs-generator)
#+end_src
