* Webs We Weave
** The Whole Enchilada
   :PROPERTIES:
   :header-args:   :tangle "./.emacs.el" :comments no
   :END:

Configure EMACS to do everything provided by this document.

Sysop is likely to use this on a daily basis.

#+BEGIN_SRC emacs-lisp
«Principle-of-Least-Astonishment»
#+END_SRC

* Literate Programming
** Org-Mode Exemple Complet Minimal
   :PROPERTIES:
   :noweb-ref: org-mode-ecm
   :END:

** Tangling
** Weaving
** Programming
* Piano Lessons
* Quiet and Pleasant
* Principle of Least Astonishment
  :PROPERTIES:
  :noweb-ref: Principle-of-Least-Astonishment
  :END:

Emacs-Lisp source code files have a name and an extension. The name is the
unique identifier for that artifact. The extension describes the representation
of that artifact. =.el= is a human readable and uncompiled. =.elc= is not human
readable and compiled. When you ask EMACS to ~load~ a file, which one should it
load?

The variable ~load-suffixes~ and ~load-file-rep-suffixes~ tell EMACS which one to
load first. The former only applies to text and compiled files. The latter
applies other representations of the file. For example, EMACS will load Gzip =.gz=
files. You may utilize these ~load~ options to develop a flexible personal
workflow.

You may configure ~load~ to combine the productivity of REPL style of development
and with the speed of compilation. Tell EMACS to prefer to load byte-compile
files first and text files second. This workflow lets you experiment with new
features and when you are ready to use them every time you compile them. This
is what you get OOTB. The only downside of this approach is when you forget
about it.

When you forget about that style of system you end up with surprising behavior.
The surprise comes when you forget to compile code and write new code that
depends on the now old version of that code. After the next build, your system
can break in surprising ways. This says something about the Sysop and not EMACS.
This system doesn't like surprises.

HELP does the simplest thing possible: when told to ~load~ a file it loads
the newest representation available.

This is the *first* thing that needs to happen in the initialization of *any*
tangled system.

#+BEGIN_SRC emacs-lisp
(setq load-prefer-newer t)
#+END_SRC

* Watch What You Eat
* Style Guide

- Code Block
  - Tell the story in speech, and then in code.
  - Consider it another paragraph and indent appropriately.
    - Never separate a paragraph and and a Code Block with a colon.
- Content
  - When importing update to conform with Style-Guide.
- Dictionary
  - Out of the Box (OOTB) :: The default configuration of EMACS.
  - Sysop :: A proper noun. The System-Operator. The human operating this EMACS
    based Org-Mode enabled literate programming system. Yourself.
  - Tangle :: A verb. Assemble a document for consumption by another program or
    machine.
  - Weave :: A verb. Prepare a document for consumption by a human.
- Entity
  - Code Snippet
    - Use ~code style~.
  - Non-Code Snippet
    - Program names, file types
    - Use =verbatim= style
  - Package
    - Same as Headline.
    - Dashes separate definition.
    - Acronyms are all upper case to distinguish from words for example "GNU"
      vs "Gnu".
- Headline
  - Capitalize nouns, verbs, and adjectives.
  - Don't capitalize conjunctions unless they are starting the definition.
  - Sell this "chapter" to the reader.
- Hyperlink
  - External
    - Exclude those easily found with a search-engine unless you are willing to
      verify their existence frequently.
  - Internal
    - Heading artifacts can be referenced so the need here is minimal to
      non-existent.
- Literate Programming
  - Comments
    - Exclude from tangle-blocks and rely on source-block for traceability
  - Noweb-Ref
    - Same as Headline.
    - Replace spaces with dashes.
    - Probably the Heading name.
- Maintenance
  - Frequently check spelling, grammar, and weasel-words.
- Plain List
  - End single sentences with a period.
- Programming Language
  - Emacs-Lisp
    - Use ~t~ for ~true~.
- Voice
  - The audience is Sysop.
  - The audience is another EMACS user.
  - Pleasant conversation style.
  - Simple and detailed.
- Word Choice
  - Use Arabic numerals.
