#+STARTUP: showeverything
* README

HELP Enables Literate Programming.

Setup:

1) [[http://orgmode.org/][Clone Org-Mode]] to =~/src/=.
   1) If necessary: [[http://orgmode.org/worg/org-hacks.html][Generating autoloads and Compiling Org without make]]
2) [[https://github.com/jwiegley/use-package][Clone Use-Package]] to =~/src/=.
3) [[https://github.com/RickMoynihan/yasnippet-org-mode][Clone yasnippet-Org-Mode]] to =~/src/=.
4) Link.
   - The Eshell directory to HELP's.
     - =ln -s ~/src/help/eshell/ ~/.emacs.d/eshell=
   - The Init file to HELP's.
     - =ln -s ~/src/help/.emacs.el ~/.emacs.el=

* Webs We Weave

** Org-Mode Exemple Complet Minimal
   :PROPERTIES:
   :noweb-ref: Org-Mode-ECM-Tangle-Block
   :header-args:   :tangle "./.org-mode-ecm.emacs.el" :comments no
   :END:

Configure EMACS to easily provide ECMs.

Sysop is likely to use this often.

Start EMACS with this command:

=open /Applications/Emacs.app --args --quick --load ~/src/help/.org-mode-ecm.emacs.el=

#+BEGIN_SRC emacs-lisp
«Principle-of-Least-Astonishment»
«Org-Mode-ECM»
#+END_SRC

** The Whole Enchilada
   :PROPERTIES:
   :header-args:   :tangle "./.emacs.el" :comments no
   :END:

Configure EMACS to do everything provided by this document.

Sysop is likely to use this daily.

Start EMACS with this command:

#+BEGIN_SRC emacs-lisp
«Org-Mode-ECM-Tangle-Block»
«Org-Mode-Helper-Functions»
«Org-Mode-Tangle»
«Watch-What-You-Eat»
«Org-Mode-Execute»
«Org-Mode-Weave»
«Org-Mode-Programming»
«Special-Operating-Procedure»
«Standard-Operating-Procedure»
«Hacking-Emacs-Lisp»
«Hacking-Org-Mode»
«Hacking-Common»
«Quiet-and-Pleasant-Appearance»
«Piano-Lessons»
#+END_SRC

=open /Applications/Emacs.app=

** Eshell
   :PROPERTIES:
   :header-args:   :tangle "eshell" :comments no
   :END:

#+BEGIN_SRC sh :tangle eshell/alias :comments no
alias clear recenter 0
alias d 'dired $1'
alias ff find-file $1
alias gb git branch $*
alias gpom git push origin master
alias gst git status
alias la ls -lha $*
alias ll ls -lh $*
#+END_SRC

* Literate Programming

This system enables you to perform 3 Literate Document activities. These
activities combine to provide a rich Literate Programming environment. Their
configuration is defined with more granularity here to make sense of how the
system is configured, where, and how it works. These activities are not
performed interactively by the user. They are automatic operations that occur
as a result of the configuration of the document itself.

The following is the guide for the default configuration of this system and how
it behaves.

Key:

- Columns
  - S :: Source document modified?
  - W :: Destination weaved-document modified?
  - T :: Destination tangled-document modified?
  - E :: Evaluation occurred?

| Activity   | S | W | T | E |
|------------+---+---+---+---|
| Tangling   | F | F | T | F |
| Evaluating | T | F | F | T |
| Exporting  | F | T | F | F |

They are separate and distinct operations and are defined as such.

The last logical action is the activity of "Programming". It is a combination of
three 3 activities listed above combined with the configuration of EMACS to do
so. This is an interactive activity performed Sysop. The results of Sysop's
activities are contained within the document. Those contents are input for the
activities here.

** Org-Mode Exemple Complet Minimal
   :PROPERTIES:
   :noweb-ref: Org-Mode-ECM
   :END:

A stable version of Org-Mode is provided OOTB. It's release cycle is tied to
EMACS release cycle. To get hot-fixes, cutting edge features, and easy patch
creation though, you need to use the version from Git.

The [[http://orgmode.org/manual/Installation.html][directions]] of how to run Org-Mode from Git are detailed and clear. The only
thing worth mentioning again is that in order to use *any* version of Org-Mode
other than the one that comes OOTB you *must* load Org-Mode *before* anything else
in your initialization file. This can be surprisingly easy to do! When you get
unexpected Org-Mode behavior be sure to stop and investigate ~org-version~ and
decide whether or not it is what you expect and prepare an ECM if necessary.

Add the Org-Mode core distribution the load path.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/org-mode/lisp")
#+END_SRC

Add the Org-Mode-Contributions distribution to the load path. The contributions
are critical to and inseparable from the core distribution.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/org-mode/contrib/lisp")
#+END_SRC

This system allows for single-character alphabetical bullet lists. For Org-Mode
to provide that, the following property must exist before Org-Mode is even
loaded. This configuration must occur here. *Never* remove this from a submitted
ECM.

#+BEGIN_SRC emacs-lisp
(setq org-list-allow-alphabetical t)
#+END_SRC

Load Org-Mode.

#+BEGIN_SRC emacs-lisp
(require 'org)
#+END_SRC

Org-Mode already uses the guillemot for demarcating noweb references, but it
does it using the work-around of just using less-than and greater-than
characters twice. That is fine. Because EMACS supports Unicode just fine though,
configure Org-Mode to use the real symbol. Another option would be to configure
Pretty-Mode. This is in the ECM section because so that I can verify behavior of
my code.

#+BEGIN_SRC emacs-lisp
(setq org-babel-noweb-wrap-start "«")
(setq org-babel-noweb-wrap-end "»")
#+END_SRC

** Helper Functions
   :PROPERTIES:
   :noweb-ref: Org-Mode-Helper-Functions
   :END:

#+BEGIN_SRC emacs-lisp
(defun help/set-org-babel-default-header-args (property value)
  "Easily set system header arguments in org mode.

PROPERTY is the system-wide value that you would like to modify.

VALUE is the new value you wish to store.

Attribution: URL `http://orgmode.org/manual/System_002dwide-header-arguments.html#System_002dwide-header-arguments'"
  (setq org-babel-default-header-args
        (cons (cons property value)
              (assq-delete-all property org-babel-default-header-args))))

(defun help/set-org-babel-default-inline-header-args (property value)
  "See `help/set-org-babel-default-header-args'; same but for inline header args."
  (setq org-babel-default-inline-header-args
        (cons (cons property value)
              (assq-delete-all property org-babel-default-inline-header-args))))

(defun help/comment-or-uncomment ()
  "Comment or uncomment the current line or selection."
  (interactive)
  (cond ((not mark-active) (comment-or-uncomment-region (line-beginning-position)
                                                      (line-end-position)))
        ((< (point) (mark)) (comment-or-uncomment-region (point) (mark)))
        (t (comment-or-uncomment-region (mark) (point)))))

(defun help/save-all-file-buffers (&rest ls)
  "Saves every buffer associated with a file

LS captures arguments when this is used as before advice."
  (interactive)
  (dolist (buf (buffer-list))
    (with-current-buffer buf
      (when (and (buffer-file-name) (buffer-modified-p))
        (save-buffer)))))

(defun help/describe-thing-in-popup ()
  "Display help information on the current symbol.

Attribution: URL `http://www.emacswiki.org/emacs/PosTip'
Attribution: URL `http://blog.jenkster.com/2013/12/popup-help-in-emacs-lisp.html'"
  (interactive)
  (let* ((thing (symbol-at-point))
         (help-xref-following t)
         (description (with-temp-buffer
                        (help-mode)
                        (help-xref-interned thing)
                        (buffer-string))))
    (help/on-gui (pos-tip-show description nil nil nil 300))
    (help/not-on-gui (popup-tip description
                                :point (point)
                                :Around t
                                :height 30
                                :scroll-bar t
                                :margin t))))

(defun help/kill-other-buffers ()
  "Kill all other buffers."
  (interactive)
  (mapc 'kill-buffer (delq (current-buffer) (buffer-list))))

(defun help/untabify-buffer ()
  "For untabifying the entire buffer."
  (interactive)
  (untabify (point-min) (point-max)))

(defun help/untabify-buffer-hook ()
  "Adds a buffer-local untabify on save hook"
  (interactive)
  (add-hook
   'after-save-hook
   (lambda () (help/untabify-buffer))
   nil
   'true))

(defun help/disable-tabs ()
  "Disables tabs."
  (setq indent-tabs-mode nil))

(defvar help/delete-trailing-whitespace-p t
  "Should trailing whitespace be removed?")

(defun help/delete-trailing-whitespace ()
  "Delete trailing whitespace for everything but the current line.

If `help/delete-trailing-whitespace-p' is non-nil, then delete the whitespace.
This is useful for fringe cases where trailing whitespace is important."
  (interactive)
  (when help/delete-trailing-whitespace-p
    (let ((first-part-start (point-min))
          (first-part-end (point-at-bol))
          (second-part-start (point-at-eol))
          (second-part-end (point-max)))
      (delete-trailing-whitespace first-part-start first-part-end)
      (delete-trailing-whitespace second-part-start second-part-end))))

(defun help/insert-timestamp ()
  "Produces and inserts a full ISO 8601 format timestamp."
  (interactive)
  (insert (format-time-string "%Y-%m-%dT%T%z")))

(defun help/insert-timestamp* ()
  "Produces and inserts a near-full ISO 8601 format timestamp."
  (interactive)
  (insert (format-time-string "%Y-%m-%dT%T")))

(defun help/insert-datestamp ()
  "Produces and inserts a partial ISO 8601 format timestamp."
  (interactive)
  (insert (format-time-string "%Y-%m-%d")))

(defun help/no-control-m ()
  "Aka dos2unix."
  (interactive)
  (let ((line (line-number-at-pos))
        (column (current-column)))
    (mark-whole-buffer)
    (replace-string "
          " "")
    (goto-line line)
    (move-to-column column)))

(defun help/indent-curly-block (&rest _ignored)
  "Open a new brace or bracket expression, with relevant newlines and indent. Src: https://github.com/Fuco1/smartparens/issues/80"
  (newline)
  (indent-according-to-mode)
  (forward-line -1)
  (indent-according-to-mode))

(defun beginning-of-line-dwim ()
  "Toggles between moving point to the first non-whitespace character, and
    the start of the line. Src: http://www.wilfred.me.uk/"
  (interactive)
  (let ((start-position (point)))
    ;; see if going to the beginning of the line changes our position
    (move-beginning-of-line nil)

    (when (= (point) start-position)
      ;; we're already at the beginning of the line, so go to the
      ;; first non-whitespace character
      (back-to-indentation))))

(defun help/lazy-new-open-line ()
  "Insert a new line without breaking the current line."
  (interactive)
  (beginning-of-line)
  (next-line)
  (newline)
  (previous-line))

(defun help/smart-open-line ()
  "Insert a new line, indent it, and move the cursor there.

This behavior is different then the typical function bound to return
which may be `open-line' or `newline-and-indent'. When you call with
the cursor between ^ and $, the contents of the line to the right of
it will be moved to the newly inserted line. This function will not
do that. The current line is left alone, a new line is inserted, indented,
and the cursor is moved there.

Attribution: URL `http://emacsredux.com/blog/2013/03/26/smarter-open-line/'"
  (interactive)
  (move-end-of-line nil)
  (newline-and-indent))

(defun help/insert-ellipsis ()
  "Insert an ellipsis into the current buffer."
  (interactive)
  (insert "…"))

(defun help/insert-noticeable-snip-comment-line ()
  "Insert a noticeable snip comment line (NSCL)."
  (interactive)
  (if (not (bolp))
      (message "I may only insert a NSCL at the beginning of a line.")
    (let ((ncl (make-string 70 ?✂)))
      (newline)
      (previous-line)
      (insert ncl)
      (comment-or-uncomment-region (line-beginning-position) (line-end-position)))))

(progn
  (defvar my-read-expression-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map read-expression-map)
      (define-key map [(control ?g)] #'minibuffer-keyboard-quit)
      (define-key map [up]   nil)
      (define-key map [down] nil)
      map))

  (defun my-read--expression (prompt &optional initial-contents)
    (let ((minibuffer-completing-symbol t))
      (minibuffer-with-setup-hook
          (lambda ()
            (emacs-lisp-mode)
            (use-local-map my-read-expression-map)
            (setq font-lock-mode t)
            (funcall font-lock-function 1))
        (read-from-minibuffer prompt initial-contents
                              my-read-expression-map nil
                              'read-expression-history))))

  (defun my-eval-expression (expression &optional arg)
    (interactive (list (read (my-read--expression ""))
                       current-prefix-arg))
    (if arg
        (insert (pp-to-string (eval expression lexical-binding)))
      (pp-display-expression (eval expression lexical-binding)
                             "*Pp Eval Output*"))))
(defun help/util-ielm ()
  "Personal buffer setup for ielm.

Creates enough space for one other permanent buffer beneath it."
  (interactive)
  (split-window-below -20)
  (help/safb-other-window)
  (ielm)
  (set-window-dedicated-p (selected-window) t))

(defun help/util-eshell ()
  "Personal buffer setup for eshell.

Depends upon `help/util-ielm' being run first."
  (interactive)
  (split-window-below -10)
  (help/safb-other-window)
  (eshell)
  (set-window-dedicated-p (selected-window) t))

(defvar help/util-state nil "Track whether the util buffers are displayed or not.")

(defun help/util-state-toggle ()
  "Toggle the util state."
  (interactive)
  (setq help/util-state (not help/util-state)))

(defun help/util-start ()
  "Perhaps utility buffers."
  (interactive)
  (help/util-ielm)
  (help/util-eshell)
  (help/util-state-toggle))

(defun help/util-stop ()
  "Remove personal utility buffers."
  (interactive)
  (if (get-buffer "*ielm*") (kill-buffer "*ielm*"))
  (if (get-buffer "*eshell*") (kill-buffer "*eshell*"))
  (help/util-state-toggle))

(defun help/ielm-auto-complete ()
  "Enables `auto-complete' support in \\[ielm].

Attribution: URL `http://www.masteringemacs.org/articles/2010/11/29/evaluating-elisp-emacs/'"
  (setq ac-sources '(ac-source-functions
                     ac-source-variables
                     ac-source-features
                     ac-source-symbols
                     ac-source-words-in-same-mode-buffers))
  (add-to-list 'ac-modes 'inferior-emacs-lisp-mode)
  (auto-complete-mode 1))

(defun help/uuid-string ()
  "Insert a string form of a UUID."
  (interactive)
  (insert (uuid-to-stringy (uuid-create))))

(defun endless/sharp ()
  "Insert #' unless in a string or comment.

SRC: URL `http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html?source=rss'"
  (interactive)
  (call-interactively #'self-insert-command)
  (let ((ppss (syntax-ppss)))
    (unless (or (elt ppss 3)
                (elt ppss 4))
      (insert "'"))))

(defun help/chs ()
  "Insert opening \"cut here start\" snippet."
  (interactive)
  (insert "--8<---------------cut here---------------start------------->8---"))

(defun help/che ()
  "Insert closing \"cut here end\" snippet."
  (interactive)
  (insert "--8<---------------cut here---------------end--------------->8---"))

(defmacro help/measure-time (&rest body)
  "Measure the time it takes to evaluate BODY.

Attribution Nikolaj Schumacher: URL `https://lists.gnu.org/archive/html/help-gnu-emacs/2008-06/msg00087.html'"
  `(let ((time (current-time)))
     ,@body
     (message "%.06f" (float-time (time-since time)))))

(defun help/create-non-existent-directory ()
  "Attribution URL: `https://iqbalansari.github.io/blog/2014/12/07/automatically-create-parent-directories-on-visiting-a-new-file-in-emacs/'"
  (let ((parent-directory (file-name-directory buffer-file-name)))
    (when (and (not (file-exists-p parent-directory))
               (y-or-n-p (format "Directory `%s' does not exist. Create it?" parent-directory)))
      (make-directory parent-directory t))))

(defun help/occur-dwim ()
  "Call `occur' with a mostly sane default.

Attribution Oleh Krehel (abo-abo): URL `http://oremacs.com/2015/01/26/occur-dwim/'"
  (interactive)
  (push (if (region-active-p)
            (buffer-substring-no-properties
             (region-beginning)
             (region-end))
          (let ((sym (thing-at-point 'symbol)))
            (when (stringp sym)
              (regexp-quote sym))))
        regexp-history)
  (call-interactively 'occur))

(defun help/util-cycle ()
  "Display or hide the utility buffers."
  (interactive)
  (if help/util-state
      (help/util-stop)
    (help/util-start)))

(defun sacha/unfill-paragraph (&optional region)
  "Takes a multi-line paragraph and makes it into a single line of text.

ATTRIBUTION: SRC https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org#unfill-paragraph"
  (interactive (progn
                 (barf-if-buffer-read-only)
                 (list t)))
  (let ((fill-column (point-max)))
    (fill-paragraph nil region)))
#+END_SRC

** Tangling
   :PROPERTIES:
   :noweb-ref: Org-Mode-Tangle
   :END:

There is a way to disable property inheritance that speeds up tangling a lot.
This is only for user-defined properties; *not* Org-Mode properties.

The problem is that you lose property inheritance which is unacceptable. Never,
never allow that. Its inconsistent with how Org-Mode works.

#+BEGIN_SRC emacs-lisp
(setq org-babel-use-quick-and-dirty-noweb-expansion nil)
#+END_SRC

*** Comments

Provide as much information as possible in the tangled artifact about the
origin artifact.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :comments "noweb")
#+END_SRC

*** Padline

~org-babel-tangle-jump-to-org~ requires padded lines. This configuration could
arguably appear in the "Programming" heading because it impacts operation. It
lives here because it *must* occur as part of the Tangling activity so that it
can be used in the Programming activity.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :padline "yes")
#+END_SRC

*** Noweb

Expand noweb references in source-blocks before:

| Activity   | Expand |
|------------+--------|
| Tangling   | T      |
| Evaluating | T      |
| Exporting  | F      |

This embraces the notion that you are telling the right thing to the
computer and the right thing to the human. By the time you get to exporting, you
ought to refer to the generated document.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :noweb "no-export")
#+END_SRC

** Evaluating
   :PROPERTIES:
   :noweb-ref: Org-Mode-Execute
   :END:

Install OB-SML.

#+BEGIN_SRC emacs-lisp
(use-package ob-sml
  :ensure t)
#+END_SRC

Org-Mode may evaluate all of the listed languages.

#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((calc . t)
   (css . t)
   (dot . t)
   (ditaa . t)
   (emacs-lisp . t)
   (js . t)
   (latex . t)
   (lilypond . t)
   (makefile . t)
   (org . t)
   (perl . t)
   (python . t)
   (plantuml . t)
   (R . t)
   (scheme . t)
   (sh . t)
   (sml . t)
   (sql . t)))
#+END_SRC

*** Eval

Never evaluate source-blocks or in-line-source-blocks on export.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :eval "never-export")
(help/set-org-babel-default-inline-header-args :eval "never-export")
#+END_SRC

Be sure to never evaluate in-line-source-blocks on export.

#+BEGIN_SRC emacs-lisp
(setq org-export-babel-evaluate nil)
#+END_SRC

*** Results

This system stores the results of evaluation in the source document. It believes
that the results are critical to the research.

Always display results like you would seem them in a REPL. For source-blocks
this means an =output= display and for in-line-source-blocks it means a =value=
display.

Replace theme each time you evaluate the block.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :results "output replace")
(help/set-org-babel-default-inline-header-args :results "value replace")
#+END_SRC

** Weaving
   :PROPERTIES:
   :noweb-ref: Org-Mode-Weave
   :END:

Load Htmlize for HTML export. Use it. Use in-line CSS.

#+BEGIN_SRC emacs-lisp
(require 'htmlize)
(setq org-html-htmlize-output-type htmlize-output-type)
(setq htmlize-output-type 'inline-css)
#+END_SRC

Load Beamer for creating reports.

#+BEGIN_SRC emacs-lisp
(require 'ox-beamer)
#+END_SRC

Load Markdown export for system compatibility.

#+BEGIN_SRC emacs-lisp
(require 'ox-md)
#+END_SRC

Make sure that exported files are Unicode UTF-8.
#+BEGIN_SRC emacs-lisp
(setq org-export-coding-system 'utf-8)
#+END_SRC

Do not preserve line-breaks when exporting instead let the destination
format handle it as it sees fit. This doesn't work like I had expected and makes
me wonder what I am confused about here. When I export to HTML text containing
linebreaks no longer has linebreaks. This is what I expect. When I export that
same text to a buffer though, the line breaks are included. Currently I use
=sacha/unfill-paragraph= on that code.
#+BEGIN_SRC emacs-lisp
(setq org-export-preserve-breaks nil)
#+END_SRC

When exporting anything, do not insert the exported content into the kill ring.
#+BEGIN_SRC emacs-lisp
(setq org-export-copy-to-kill-ring nil)
#+END_SRC

By default I never want a table of contents generated. It is so easy to enable
it with a property, it will be fine to turn it off.

#+BEGIN_SRC emacs-lisp
(setq org-export-with-toc nil)
#+END_SRC

On export, maintain the literal spacing as found in the source block. Obviously
this is important for make-files. It is really important everywhere because
anything else would violate the law of least surprise.

#+BEGIN_SRC emacs-lisp
(setq org-src-preserve-indentation t)
#+END_SRC

*** Exports

Always share source blocks and their results. Whether or not to generate a
result for a particular source block is configured per-block. If you don't want
to share a result for a source block then disable storage of results on that
block.

#+BEGIN_SRC emacs-lisp
(help/set-org-babel-default-header-args :exports "both")
#+END_SRC


*** KOMA-Script

I enjoy writing letters. I enjoy reading letters. LaTeX produces letters that
are easy to print and read. Org provides a [[http://orgmode.org/worg/exporters/koma-letter-export.html][KOMA Script exporter]] for [[https://www.ctan.org/pkg/koma-script?lang%3Den][KOMA-script]].
The Org documentation mentions that the user should read the [[http://orgmode.org/cgit.cgi/org-mode.git/plain/contrib/lisp/ox-koma-letter.el][ox-koma-letter.el]]
header documentation.

The [[https://www.ctan.org/pkg/babel?lang%3Den][babel]] packages is mentioned in the Org documentation. The package
documentation explains that it should be used with LaTeX, but not XeTeX. Some
time ago I decided to stick with LaTeX.

Load the KOMA exporter.

#+BEGIN_SRC emacs-lisp
(eval-after-load 'ox '(require 'ox-koma-letter))
#+END_SRC

- Understanding KOMA and how to use it
  - There are 4 ways to set letter metadata, listed "from the most specific to
    the most general" (not sure exactly what this statement means, and the conclusion of my notes tries to make sense of what is really going on here and what is the best way to do things)
    - Org option lines (ORG)
    - Separate Org latex classes (LTX)
    - Emacs Lisp variables (LISP)
    - Letter Class Option files (LCO)
- Notes and thoughts on the ways to use it
  - LTX
    - By following the setup directions, you do this, creating "my-letter" class
    - Familiar and easy if you already know LaTeX
      - At some point in your workflow, you *must* define a class to use, anyway
    - Very easy to do, just define the class template and set =org-koma-letter-default-class=
  - ORG
    - Simple way that makes it very easy to just focus on the document content
    - This metadata takes highest priority in the workflow
      - So you should set your typical defaults in LISP or LCO and customize it
        here. This is exactly what I wanted to know.
      - This lets you do your tweaking in each unique file while relying on the
        most common defaults defined elsewhere
  - LISP
    - Very familiar style of configuring things
  - LCO
    - LCO == Letter Class Option files
    - LCO files are TeX
    - They are included in the generated TeX source code from the letter
    - Gives *full* access to KOMA-Script
      - Big deal, because not everything is exposed through ORG or LISP
      - Also gives full access to any and all TeX and LaTeX code
    - LCO files are a KOMA-Script thing, so they are a LaTeX thing
    -
      #+begin_quote
      Letter metadata set in LCO files overwrites letter metadata set in Emacs
      variables but not letter metadata set in the Org file.
      #+end_quote
    - When you include multiple LCO files, they are evaluated LIFO. Properties
      are set as they first appear, and are not set again. Say you include
      "MyGeneralStuffForAnyLetter.lco" and then include
      "MyStuffSpecificToThisLetter.lco". The specific stuff will get set first.
      Then general stuff will get set last.
      - Surely there is a better way to phrase this. I will work on that.
- Recommendations
  - What is the easiest way to start using KOMA-Script based on what you know
    today?
  - If you don't know any of the approaches
    - Then choose between learning LaTeX and Org
  - If you only know LaTeX
    - Then you will use the LTX/LCO metadata approach
  - If you only know ORG
    - Then you will use the ORG metadata approach
  - If you only know ORG and LISP
    - Then you will use the LISP approach for general metadata and the ORG
      approach specific metadata
  - If you know LTX/LCO, ORG, and LISP
    - Then you have total flexibility
    - The fact is that
      - ORG settings always trump LTX/LCO and LISP
      - LISP settings are a subset of all of the settings available in
        KOMA-Script, so you will always have to fall back to LTX/LCO if you want
        to use unexposed features
      - LCO files are just plain old LaTeX, which you already know
    - So the best thing to do
      - Is to use ORG for letter-specific settings
      - And LTX for general settings
      - Everything is a lot simpler this way because
        - One less metadata approach to keep track of
        - All KOMA-Script features are present
        - Need to learn details of KOMA-Script package anyway

Configure the default class.

[[https://tex.stackexchange.com/questions/102922/how-can-i-get-us-letter-output-from-koma-scripts-scrlttr2-class][This]] post explains how to default the US letter size. That is the likely default
for my printed correspondence.

#+BEGIN_SRC emacs-lisp
(eval-after-load 'ox-koma-letter
  '(progn
     (add-to-list 'org-latex-classes
                  '("my-letter"
                    "\\documentclass[paper=letter, pagesize, fontsize=10pt, parskip]{scrlttr2}
\\usepackage[english]{babel}
\\usepackage[osf]{mathpazo}"))

     (setq org-koma-letter-default-class "my-letter")))
#+END_SRC

There are two formats for the letters: [[http://orgmode.org/w/?p%3Dworg.git%3Ba%3Dblob%3Bf%3Dexporters/koma-letter-new-example.org%3Bh%3D180a9a0e10dd8f7483a67946daf36732c316f821%3Bhb%3D180a9a0e10dd8f7483a67946daf36732c316f821][heading-based]] and [[http://orgmode.org/w/?p%3Dworg.git%3Ba%3Dblob%3Bf%3Dexporters/koma-letter-example.org%3Bh%3De21b8b00c3e895be9dd573d02ea84b08796296a3%3Bhb%3De21b8b00c3e895be9dd573d02ea84b08796296a3][property-based]].

Set up my default LCO files.

#+BEGIN_SRC emacs-lisp
(setq org-koma-letter-class-option-file "UScommercial9 KomaDefault")
#+END_SRC


* Piano Lessons
   :PROPERTIES:
   :noweb-ref: Piano-Lessons
   :END:

** A Fine Cup of EMACS

Every EMACS user ought to have a [[http://shop.fsf.org/product/gnu-emacs-reference-mugs/][Emacs Reference Mug]] at their desk. The mug
invites other users to ask questions. Give the mug as a gift to every user you
know who would benefit from learning EMACS. The mug reminds us all that EMACS is
the perfect configuration of EMACS. It is available on every machine. When you
break your system, you can always fall back to the good and reliable default
EMACS configuration to get your system up and running again. The OOTB
configuration of EMACS is one of the most important system configurations that
you will every find. That is why it is important never to ruin it.

This system wants to maximize accessibility for new users. It wants anyone to be
able to download and use it without surprises. It wants the mug to serve as a
fine reference for anyone to use. It wants to keep things simple and familiar so
that anyone who has learned EMACS OOTB can use it pleasantly and productively.
These goals are essential to configuring the keyboard for this system. This
system will always respect the POLA.

** A Keyboard on Every Desk

The configuration of the keyboard on an EMACS system can completely change the
experience. No keyboard makes it impossible. A Kinesis Ergo makes it feel
really good. Soft keys make it feel soft; hard keys make it feel faster. The
[[http://xahlee.info/kbd/dvorak_and_all_keyboard_layouts.html][layout of letters]] is claimed to make you "more productive" using statistics.
You may even study the statistics of your own writing and choose a layout
optimized for you. The ways to configure your keyboard are limitless because
everyone is unique. How to get the best configuration tips for your system? Do
what works for everyone.

Choose a keyboard that will satisfy 80% of EMACS users using 80% of the
keyboards out there. Make this system easy to use on any one of those keyboards.
Make this system easy to use in English. Make this system easy to use with
average hand strength using two hands. These goals are essential to configuring
the keyboard for this system.

** A Display with Every Keyboard

Every system requires an output. You have two options. The first is a terminal
that only displays characters. The second is a display that provides detailed
graphics. "Display" is the EMACS term for a GUI.

Some users prefer the former. Some users prefer the latter. Some users prefer to
use a $4000USD machine to emulate the latter. Both are good options.

This system is configured to work pleasantly for either type of output.

** A Full Pot of EMACS on Every Desk

*** Keyboard Layout & Operation

- Use QWERTY layout.
  - Everyone knows it.
  - Easy to learn.
  - Available on every keyboard.
  - Inexpensive.
  - When graduation time comes, plenty of great alternatives available like
    DVORAK and Colemak.
- Keep hands in home position as much as possible.
  - Every finger is strong in the home position so RSI reduced.
  - Single key presses are easy there.
- Table-bang the shift, caps-lock and enter keys.
  - Table-bang is a position of your hand. Make it by:
    - Starting with your hands in the home position.
    - Make a "high-five" with both of them parallel to the keyboard.
    - Turn your left hand counter-clockwise and right hand clockwise to make
      them perpendicular to the keyboard.
    - Squeeze all of your fingers together.
    - Push the keys using the side of your Pinky.
    - In this position you are using the strength of all of your fingers.
  - Never use those key using your Pinky alone.
  - Practice depends 100% on user-discipline.
- Try to achieve balance with meta keys.
  - Provide same key of each side of the keyboard.
- Be conscious of key operations [[http://ergoemacs.org/emacs/emacs_key_notation_return_vs_RET.html][on different outputs]].
  - Always provide both.
  - Note what is getting stomped on.
  - For return bind to:
    - =RET= in the terminal.
    - =<return>= in the GUI.
  - Also for tab =TAB= vs =C-i=.
  - Also for escape =ESC= vs =C-[=

*** Understanding Your Cognitive Landscape.

You operate within a cognitive landscape. Every moment you are in a single
=place=. While residing in each =place= you perform logically related =activities=.
Activities facilitate logical actions like modification within that =place=.
Modifications are performed objects. Objects include things like the contents of
a buffer, contents of memory, or the file that backs a buffer. While performing
those =activities= there is a logical sense of "flow". That should never be
interrupted. Usually an interruption occurs when you are going to go to a new
=place=. The =distance= between =places= is measured in the similarity between the
=actions= that you find there. As you develop these ides it will be obvious where
key-bindings should go

*** Key-Bindings Take You to Places to Perform Activities

OOTB you wil be visiting many =places= and performing many =activities=. EMACS comes
with a good configuration that minimizes =distance=. This isn't worth changing.
You can use EMACS for a lifetime without ever having to customize any of the
key-bindings. This is what lets anyone use your system. This is what lets you
use the system with =-Q= when you break it. You need to decide if you every want
to alter the default configuration. This system does not want to. It wants to
keep EMACS true to EMACS and your hands happy. To satisfy those goals the
following practices were defined.

- 99.999% of the time never bind to the =C= or =M= name-space.
  - They are for system key-bindings. You can break them. Don't.
  - In theory =C-c= is the "user name-space" but packages stomp on this all of the
    time anyway so don't use it.
  - Some bindings are just too valuable to pass up:
    - =C-;=
      - Your hands are in the home position already.
    - Every modifier key with return.
- Never bind to =F= keys.
  - They are a painful stretch on most keyboards.
  - Some require a lone Pinky with is worse.
  - Most operating systems bind actions to them OOTB anyway.
  - EMACS comes with key-bindings OOTB.
- Don't try to set up a Hyper-key.
- Use shift as a name-space expansion vehicle.
  - Shift doubles every name-space in which you use it.
  - Use cautiously, not every name-space vehicle supports it.
- About the =s= (super) name-space.
  - In theory it is the best place for user-defined key-bindings because
    EMACS OOTB uses =C= and =M= completely leaving =s= mostly open.
  - In practice =C= and =M= are running out of space because there are a lot of
    new packages being added to EMACS. Most new packages are binding key
    in the =s= name-space.
  - This system reserves =s= completely for Sysop.

These practices say nothing about the =places= or =activities= that you choose to
peform. The practices only look at the key-binding configuration. There are a
limited number of keys on a keyboard and there are physical limitations on your
hands. Along with the previous assuptions it may look like there are less.
Fortunately it just looks that way and it isn't true. There are a lot of
powerful ways to "go places" with EMACS. The next heading contains my attempt.

*** How to Get There Pleasantly and Quickly

You need to learn how to use EMACS. You need to develop a personal preference.
You need to develop an idea of =places= and =activities= and =distance=. The following
headings are delineated by breaks in flow.

The examples try to talk about doing those things and do it by exploring:

- "going places to do things".
- "how quickly I will get there and how long I will be there"
- "how quickly I want to go somewhere else".

They were initially described by the properties:

- Actions :: The number of related actions in that place.
- Expertise :: The level of skill and speed with which you are performing the
  activity.
- Relationship :: How closely those activities are related in the current place.
- Frequency :: How many times you perform these actions when you here.

The relationship between "doing those things" and those 4 properties is still
unclear and being explored.

**** =s=
      :PROPERTIES:
      :Actions:          High
      :Expertise:        High
      :Relationship:     High
      :Frequency:        High
      :END:

- =Actions= here are for the =place= inside of the buffer itself. They are for
  immediate acting upon the contents of the buffer. They are logically
  related, used frequently, and likely to be memorized.
- When you come here, you are likely to stay for some time before getting
  out.
- Only use single key bindings; anything more may be a new logical
  name-space and may use a Hydra.
- Split the home sides of the keyboard in half.
- The left side of the keyboard should be use for operations common to
  every mode.
  - For example ~goto-line~ and ~ispell~.
  - It has 15 bindings available; 20 if you use 1-5. 40 if you shift them.
- The right side of the keyboard should be used operations specific to the
  current major mode.
  - For example in Org-Mode navigating between source-blocks and
    evaluating them.
  - It has 19 bindings available; 26 if you use 6-=. 52 if you shift them.

For example, in Org-Mode:

- I traverse the entire document very quickly with
  ~org-babel-previous-src-block~ and and ~org-babel-next-src-block.~
- I execute source-blocks.
- I edit source-blocks.

Every activity is related to reading, modifying, executing, and tangling code.

**** =Key-Chord=

Key-Chord is intriguing because it works on every keyboard. It is powerful
because it can you bring you to any =place= easily. It is good for taking you
places in two differnt kinds of scenarios.

One example is grammar-checking. There are a few ways to do that. I don't
remember them all. In a given mode I want to see a list of all the ways.
I really just want to see all of the stuff that I value for a given mode and
don't use frequently.

Another example are things that I value for a mode and use a lot but are not
logically related to other activities in that place. For example moving the
mark around and going to lines are performed a lot so they need to be done
quickly and left. This is a place where key-chords and the shift modifier are
a fast and intuitive way to go places.

***** Single-Key Key-Chord Name-Space.
      :Actions:          High
      :Expertise:        Low
      :Frequency:        High
      :Relationship:     Low

- Nice if you don't mind hitting the same key twice.
- You will use come here often, perform your single =action=, and be done
  and leave very frequently and quickly.
- Using alphabetical characters always results in unpleasant surprises.
- Harder for breakage but it still occurs.
  - =#FF= color code.
  - =cc= carbon copy.
  - JJ nick-name.
- Symbols are more likely to be safer bets.
  - Only use the symbols.
    - 8 if you use rows 3-4; 16 if you shift.
    - Fifth row has 13; 26 with shift.
- Good vehicle to reach a Hydra.

***** Two-Key Key-Chord Name-Space.
      :Actions:          Low
      :Expertise:        High
      :Frequency:        High
      :Relationship:     Low

- Very attractive.
- Nice if you don't like hitting the same key twice.
- Easy to use all fingers.
  - Finger strength is not an issue here; use any of them.
- Unexpected breakage very easy.
  - =cd= in ~=eshell=~.
- Use sparingly.
- Not worth analyzing ideal combinations; just use it and see if it
  doesn't break.
- Bringing over existing bindings. They are all for every mode so I will
  keep it that way.

**** =Hydra=
      :PROPERTIES:
      :Actions:          High
      :Expertise:        Low
      :Frequency:        Low
      :Relationship:     High
      :END:

- Sometimes you want to do something in a =place= but you aren't sure what
  and you aren't sure where you will go next from there. For example you
  might want to perform an Org-Mode =action= that is important but you don't
  really use much. For example exporting to HTML might not be common for
  you but you value.
- =Hydras= can be used for very related actions too. The difference between
  the =s= name-space is the distance between them and where you are now.
  In the =s= namespace you go there very quickly. For =Hydras= sometimes you
  can get the fast and sometimes more slowly. They are complementary to
  every name-space.

For example, in Org-Mode I am still learning about functions and haven't used
them much and forget their names. It is faster to put them in a Hydra. If they
get used a lot, I will add them to =s=.

*** Building Your Own Keyboard

As your mastery of EMACS grows so too will your desire to build your own
keyboard. It is natural. As you explore various dimensions of expression you
will have a lot of fun. You will act more quickly and skillfully. Even with the
goals of this system in place the desire grows.

3D printing is one area worth exploring. A lot of EMACS users design and print
their own custom keyboards. That looks very fun. [[http://scripts.sil.org/cms/scripts/page.php?site_id%3Dnrsi&id%3Dukelele][Ukulele]] is softer way to
explore your keyboard. Reading its user manual is important. It contains ideas
about stack-able-environments for bindings. You may use Ukulele or Hydras to do
the same thing. [[https://pqrs.org/osx/karabiner/][Karabiner]] is a nice way to re-map your keys. It's easiest
adjustment is to make return act as return when pressed alone and as control
when pressed with another key. That introduces a symmetry to your keyboard which
can be helpful. All of those dimensions are worth exploring.

When I explored them I felt that they led me further away from the majority of
users. Every time explored a different key-mapping (not key-binding) it reduced
accessibility for new users. Each time I tried to work around that hiccup. The
last pursuit was =;= and space.

It would be great to set up your keyboard with the meta keys on the bottom
like this:

#+BEGIN_EXAMPLE
+---------------------------------------+
| +-----+                       +-----+ |
| |RET  |                       |  RET| |
| +-----+                       +-----+ |
| +------+                     +------+ |
| |SHIFT |                     | SHIFT| |
| +------+                     +------+ |
|        +-+ +-+ +-----+ +-+ +-+        |
|        |s| |M| |C/spc| |M| |s|        |
|        +-+ +-+ +-----+ +-+ +-+        |
|                                       |
+---------------------------------------+
#+END_EXAMPLE

Karabiner was too slow for my typing speed though. It [[https://www.reddit.com/r/emacs/comments/38qllb/karabiner_space_as_control/][happens]]. It seemed like a
minimal change to use Ukelele to:

- Make space send =C=
- Make =;= send space
- Make ='= a dead key
  - In it's dead key state make
    - =;= \rarr =;=
    - =:= \rarr =:=
    - ='= \rarr ='=
    - ="= \rarr ="=

The trouble is that it violates the POLA. Therefore, I left it alone and stuck
with a simple "Get C on both sides".

That has worked out very well. It is very easy to do on every operating system.
It holds true to the values of this system. When you develop an idea of =places= and
how often you go there the key-mapping becomes more obvious. Make it easy to get
to key-bindings that take you to familiar places. For this system it is the home
keys, =s=, and =key-chord=. Make those keys more easily accessible. =C= and =M= often
have symmetric-definitions. =s= and =SHIFT= also often have symmetric definitions in
this system (mostly through Key-Chords). Therefore those key-mappings are kept
close together

#+BEGIN_EXAMPLE
+---------------------------------------+
| +-----+                       +-----+ |
| |s    |                       |s/ret| |
| +-----+                       +-----+ |
| +------+                     +------+ |
| |SHIFT |                     | SHIFT| |
| +------+                     +------+ |
|        +-+ +-+ +-----+ +-+ +-+        |
|        |M| |C| |spc  | |C| |M|        |
|        +-+ +-+ +-----+ +-+ +-+        |
|                                       |
+---------------------------------------+
#+END_EXAMPLE

** Take a Sip

Because Use-Package is used in this system, the binding definitions often live
in the call itself.

*** Left Side

VC activities.

#+BEGIN_SRC emacs-lisp
(define-prefix-command 'help/vc-map)
(global-set-key (kbd "s-t") #'help/vc-map)
(define-key help/vc-map "e" #'help/safb-vc-ediff)
(define-key help/vc-map "d" #'help/safb-vc-diff)
(define-key help/vc-map "u" #'help/safb-vc-revert)
(global-set-key (kbd "s-f") #'help/safb-help-vc-next-action)
#+END_SRC

Go to a line.

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "fg" #'goto-line)
#+END_SRC

Pop the mark back.

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "FG" #'pop-to-mark-command)
#+END_SRC

Do the /right thing/ for getting to the start of the line.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-a") #'beginning-of-line-dwim)
#+END_SRC

Occur has 3 cases. I like to use it to explore the unknown.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-s p") 'gcr/occur-dwim)
#+END_SRC

Simpler buffer movement.

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "fv" #'help/safb-other-window)
#+END_SRC

Toggle utility buffers ("logical F" key, so left side; "logical J" key on
right).

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "f9" #'help/util-cycle)
#+END_SRC

Hide and show code blocks.

#+BEGIN_SRC EMACS-LISP
(global-set-key (kbd "s-b") 'hs-toggle-hiding)
#+END_SRC

***  Left & Right Side

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "qi" #'help/comment-or-uncomment)
#+END_SRC

Make =ispell= accessible.

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "qp" #'ispell)
(key-chord-define-global "qo" #'ispell-word)
#+END_SRC

Writegood too.

#+BEGIN_SRC emacs-lisp
(key-chord-define-global "wm" #'writegood-mode)
(key-chord-define-global "wl" #'writegood-grade-level)
(key-chord-define-global "wz" #'writegood-reading-ease)
#+END_SRC

Use the default Langtool bindings.

#+BEGIN_SRC emacs-lisp
(define-prefix-command 'help/langtool-map)
(key-chord-define-global "qk" #'help/langtool-map)
(define-key help/langtool-map "c" #'langtool-check-buffer)
(define-key help/langtool-map "C" #'langtool-correct-buffer)
(define-key help/langtool-map "j" #'langtool-goto-previous-error)
(define-key help/langtool-map "k" #'langtool-show-message-at-point)
(define-key help/langtool-map "l" #'langtool-goto-next-error)
(define-key help/langtool-map "q" #'langtool-check-done)
#+END_SRC

*** Right Side

Try to reserve the right side for mode-specific activities.

*** Exceptions

Return.

Do smart new line inside, indenting given the mode.

#+BEGIN_SRC emacs-lisp
(help/not-on-gui (global-set-key (kbd "s-RET") #'help/smart-open-line))
(help/on-gui (global-set-key (kbd "s-<return>") #'help/smart-open-line))
#+END_SRC

Scroll the whole buffer by one line keeping the cursor with it.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-n") (kbd "C-u 1 C-v"))
(global-set-key (kbd "M-p") (kbd "C-u 1 M-v"))
#+END_SRC

Use a nicer =eval-expression= approach.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "s-:") #'my-eval-expression)
#+END_SRC

* Special Operating Procedure
   :PROPERTIES:
   :noweb-ref: Special-Operating-Procedure
   :END:

The following code and packages are special to this configuration. They provide
critical functionality for configuring the rest of the system. They provide
ideas that make the entire system usable, productive, expressive, and fast.

** Display

Make it easy to conditionally evaluate code when running with a graphical
display.

#+BEGIN_SRC emacs-lisp
(defmacro help/on-gui (statement &rest statements)
  "Evaluate the enclosed body only when run on GUI."
  `(when (display-graphic-p)
     ,statement
     ,@statements))

(defmacro help/not-on-gui (statement &rest statements)
  "Evaluate the enclosed body only when run on GUI."
  `(when (not (display-graphic-p))
     ,statement
     ,@statements))

#+END_SRC

** Evaluation

Evaluate code only after package load.

#+BEGIN_SRC emacs-lisp
(defmacro help/diminish (mode)
  "Diminish this mode after it is loaded."
  (interactive)
  `(eval-after-load ,mode
     (diminish ,mode)))
     #+END_SRC

** Keyboard

Key-Chord mode is amazing. Piano-Lessons shows you how.

#+BEGIN_SRC emacs-lisp
(use-package key-chord
  :ensure t
  :config
  (key-chord-mode t)
  (setq key-chord-two-keys-delay 0.1))
#+END_SRC

Echo keystrokes immediately.

#+BEGIN_SRC emacs-lisp
(setq echo-keystrokes 0.02)
#+END_SRC

** Libraries

Dash is nice to use.

#+BEGIN_SRC emacs-lisp
(use-package dash
  :ensure t
  :config
  (dash-enable-font-lock))
(use-package dash-functional
  :ensure t)
#+END_SRC

F is nice to use.

#+BEGIN_SRC emacs-lisp
(use-package f
  :ensure t)
#+END_SRC

S is nice to use.

#+BEGIN_SRC emacs-lisp
(use-package s
  :ensure t)
#+END_SRC

Generate a UUID.

#+BEGIN_SRC emacs-lisp
(use-package uuid
  :ensure t)
#+END_SRC

** Modeline

Reduce information about modes in the Modeline.

#+BEGIN_SRC emacs-lisp
(use-package diminish
             :ensure t)
#+END_SRC

Show the file size.

#+BEGIN_SRC emacs-lisp
(size-indication-mode)
#+END_SRC

Show the column number.

#+BEGIN_SRC emacs-lisp
(column-number-mode t)
#+END_SRC

** OSX

Make it easy to evaluate code only when running on OSX.

#+BEGIN_SRC emacs-lisp
(defmacro help/on-osx (statement &rest statements)
  "Evaluate the enclosed body only when run on OSX."
  `(when (eq system-type 'darwin)
     ,statement
     ,@statements))
#+END_SRC

Pull in the =ENVIRONMENT= variables because the GUI version of EMACS does not.

#+BEGIN_SRC emacs-lisp
(help/on-osx
 (use-package exec-path-from-shell
   :ensure t
   :config
   (exec-path-from-shell-initialize)))
#+END_SRC

Configure the meta keys.

Enable the =super= key-space.

#+BEGIN_SRC emacs-lisp
(help/on-osx
 (setq mac-control-modifier 'control)
 (setq mac-command-modifier 'meta)
 (setq mac-option-modifier 'super))
#+END_SRC

EMACS dialogues don't work OSX. They lock up EMACS.

This is a known issue. [[https://superuser.com/questions/125569/how-to-fix-emacs-popup-dialogs-on-mac-os-x][Here]] is the solution.

#+BEGIN_SRC emacs-lisp
(help/on-osx
 (defun help/yes-or-no-p (orig-fun &rest args)
   "Prevent yes-or-no-p from activating a dialog."
   (let ((use-dialog-box nil))
     (apply orig-fun args)))
 (advice-add 'yes-or-no-p :around #'help/yes-or-no-p)
 (advice-add 'y-or-n-p :around #'help/yes-or-no-p))
#+END_SRC

** Windows

Make it easy to evaluate code only when running on Windows.

#+BEGIN_SRC emacs-lisp
(defmacro help/on-windows (statement &rest statements)
  "Evaluate the enclosed body only when run on Microsoft Windows."
  `(when (eq system-type 'windows-nt)
     ,statement
     ,@statements))
#+END_SRC

Provide the proper shell.

#+BEGIN_SRC emacs-lisp
(help/on-windows
 (setq shell-file-name "cmdproxy.exe"))
#+END_SRC

Enable the =super= key-space.

#+BEGIN_SRC emacs-lisp
(help/on-windows
 (setq w32-lwindow-modifier 'super)
 (setq w32-rwindow-modifier 'super))
#+END_SRC

* Standard Operating Procedure
   :PROPERTIES:
   :noweb-ref: Standard-Operating-Procedure
   :END:

Configure EMACS to maximum utility.

** Buffer

Maintain buffers across sessions. Desktop-Save-Mode persists very part of the
buffer. If you upgrade a package that uses buffer-variables that have changed
you may get unexpected behavior. Close all buffers and open them again after
making such breaking changes.

#+BEGIN_SRC emacs-lisp
(desktop-save-mode t)
(setq desktop-restore-eager 10)
#+END_SRC

Provide expected "Undo" functionality.

#+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :ensure t
  :config
  (global-undo-tree-mode 1)
  (help/diminish #'undo-tree-mode))
#+END_SRC

Ensure that buffers end with a new line. This works in company with Org-Mode
source-blocks that probably don't need a newline.

#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
#+END_SRC

Easily wrap the current region.

#+BEGIN_SRC emacs-lisp
(use-package wrap-region
  :ensure t
  :config
  (wrap-region-add-wrapper "*" "*" nil 'org-mode)
  (wrap-region-add-wrapper "/" "/" nil 'org-mode)
  (wrap-region-add-wrapper "_" "_" nil 'org-mode)
  (wrap-region-add-wrapper "=" "=" nil 'org-mode)
  (wrap-region-add-wrapper "~" "~" nil 'org-mode)
  (wrap-region-add-wrapper "+" "+" nil 'org-mode)
  (help/diminish #'wrap-region-mode)
  (wrap-region-global-mode))
#+END_SRC

If you are on the end of a line, and go up or down, then go to the end of
line on that new line. Do not account for anything special about the character
there.

#+BEGIN_SRC emacs-lisp
(setq track-eol t)
(setq line-move-visual nil)
#+END_SRC

Take the cursor with scroll activities.

#+BEGIN_SRC emacs-lisp
(setq scroll-preserve-screen-position t)
#+END_SRC

More easily visualize tabular data. Considered to non-subjective.

#+BEGIN_SRC emacs-lisp
(use-package stripe-buffer
  :ensure t)
#+END_SRC

End sentences with a single space.

#+BEGIN_SRC emacs-lisp
(setq sentence-end-double-space nil)
#+END_SRC

Ban white-space at end of lines, globally.

#+BEGIN_SRC emacs-lisp
(add-hook #'write-file-hooks #'help/delete-trailing-whitespace)
#+END_SRC

Intelligently select the current char, then word, then object, then block,
then document.

#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :ensure t
  :config
  (global-set-key (kbd "s-d") #'er/expand-region))
#+END_SRC

** Code Folding

#+BEGIN_SRC emacs-lisp
(require 'hideshow)
(setq hs-hide-comments-when-hiding-all t)
(setq hs-isearch-open t)
(defun display-code-line-counts (ov)
  "Displaying overlay content in echo area or tooltip"
  (when (eq 'code (overlay-get ov 'hs))
    (overlay-put ov 'help-echo
                 (buffer-substring (overlay-start ov)
                                   (overlay-end ov)))))
(setq hs-set-up-overlay 'display-code-line-counts)
(defun help/goto-line (&rest args)
  "How do I get it to expand upon a goto-line? hideshow-expand affected block when using goto-line in a collapsed buffer."
  (save-excursion
    (hs-show-block)))
(advice-add #'goto-line :after #'help/goto-line)
(eval-after-load "hideshow" '(diminish 'hs-minor-mode))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(help/diminish #'visual-line-mode)
#+END_SRC

** Describing Objects

Easily describe just about anything.

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "s-r") 'help/describe-thing-in-popup)
#+END_SRC

** Evaluation

#+BEGIN_SRC emacs-lisp
(setq-default eval-expression-print-level nil)
#+END_SRC

Allow most commands.

#+BEGIN_SRC emacs-lisp
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)
(put 'narrow-to-region 'disabled nil)
#+END_SRC

** Encryption

Easy to use file-based AES encryption.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path (getenv "CCRYPT"))
(require 'ps-ccrypt "ps-ccrypt.el")
#+END_SRC

** Eshell

Provide a cross-platform command line shell that is a first-class EMACS citizen.

Commands input in eshell are delegated in order to an alias, a built in command,
an Elisp function with the same name, and finally to a system call. Semicolons
separate commands. =which= tells you what implementation will satisfy the call
that you are going to make. The flag =eshell-prefer-lisp-functions= does what it
says. =$$= is the result of the last command. Aliases live in
=eshell-aliases-file=. History is maintained and expandable. =eshell-source-file=
will run scripts. Since Eshell is not a terminal emulator, you need to configure
it for any commands that need to run using a terminal emulator by adding it to
to =eshell-visual-commands=.

#+BEGIN_SRC emacs-lisp
(setq eshell-prefer-lisp-functions nil
      eshell-cmpl-cycle-completions nil
      eshell-save-history-on-exit t
      eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'")

(eval-after-load 'esh-opt
  '(progn
     (require 'em-cmpl)
     (require 'em-prompt)
     (require 'em-term)
     (setenv "PAGER" "cat")
     (add-hook 'eshell-mode-hook
               (lambda ()
                 (message "Welcome to Eshell.")
                 (setq pcomplete-cycle-completions nil)))
     (add-to-list 'eshell-visual-commands "ssh")
     (add-to-list 'eshell-visual-commands "tail")
     (add-to-list 'eshell-command-completions-alist
                  '("tar" "\\(\\.tar|\\.tgz\\|\\.tar\\.gz\\)\\'"))))
#+END_SRC

The =eshell= configuration is a version controlled directory

#+BEGIN_SRC emacs-lisp
(defconst gcr/eshell-dir "~/.emacs.d/eshell")
(defun gcr/warn-eshell-dir ()
  "Warn of eshell misconfiguration."
  (interactive)
  (unless (and (f-symlink? gcr/eshell-dir)
             (f-directory? gcr/eshell-dir))
    (warn
     "Could not find the eshell directory at: %S. Eshell will continue to function albeit without your customizations."
     gcr/eshell-dir)))
(gcr/warn-eshell-dir)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq eshell-prompt-regexp "^.+@.+:.+> ")
(setq eshell-prompt-function
      (lambda ()
        (concat
         (user-login-name)
         "@"
         (system-name)
         ":"
         (eshell/pwd)
         "> ")))
#+END_SRC

** File Based System

This system uses artifacts stored in files. It tries to persiste file-stores
every chance it gets without interrupting the user's flow.

Don't create backup files. Instead Git for versioning

Automatically back file-stores if no activity has occurren.

#+BEGIN_SRC emacs-lisp
(setq auto-save-default t)
(setq make-backup-files nil)
(setq auto-save-visited-file-name t)
(setq auto-save-interval 0)
(setq auto-save-timeout (* 60 5))
#+END_SRC

Backup file-stores when the frame loses focus.

#+BEGIN_SRC emacs-lisp
(add-hook 'focus-out-hook #'help/save-all-file-buffers)
#+END_SRC

Backup file-stores before the system exits.

#+BEGIN_SRC emacs-lisp
(advice-add #'save-buffers-kill-terminal :before #'help/save-all-file-buffers)
#+END_SRC

Always keep buffers in-sync with changes in-file.

#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode 1)
#+END_SRC

Save all file befores before common activities. Functions are easier to
use than advice.

#+BEGIN_SRC emacs-lisp
(defun help/safb-help-vc-next-action ()
  (interactive)
  (help/save-all-file-buffers)
  (help/vc-next-action))

(defun help/safb-vc-ediff ()
  (interactive)
  (help/save-all-file-buffers)
  (vc-ediff nil))

(defun help/safb-vc-diff ()
  (interactive)
  (help/save-all-file-buffers)
  (vc-diff nil))

(defun help/safb-vc-revert ()
  (interactive)
  (help/save-all-file-buffers)
  (vc-revert))

(defun help/safb-magit-status ()
  (interactive)
  (help/save-all-file-buffers)
  (magit-status))

(defun help/safb-org-babel-tangle ()
  (interactive)
  (help/save-all-file-buffers)
  (let ((start (current-time)))
    (message (concat "org-babel-tangle BEFORE: <"
                     (format-time-string "%Y-%m-%dT%T%z")
                     ">"))
    (org-babel-tangle)
    (let* ((dur (float-time (time-since start)))
           (msg (format "Tangling complete after: %.06f seconds" dur)))
      (message (concat "org-babel-tangle AFTER: <"
                       (format-time-string "%Y-%m-%dT%T%z")
                       ">"))
      (message msg)
      (help/on-gui (alert msg :title "org-mode")))))

(defun help/safb-other-window ()
  (interactive)
  (help/save-all-file-buffers)
  (other-window 1))
#+END_SRC

Future candidates:
- avy jump
- dired
- eshell
- ess-rdired
- eval-defun
- eval-region
- gcr/newline
- goto-line
- ido-switch-buffer
- ielm
- ispell
- ispell-word
- langtool-check-buffer
- log-edit-done
- newline-and-indent
- next-line
- org-export-dispatch
- org-latex-export-to-pdf
- org-return
- org-return
- pop-to-mark-command
- previous-line
- sp-newline
- with-current-buffer
- writegood-mode

Try to visit a non-existent file and get prompted to create its parent
directories.

#+BEGIN_SRC emacs-lisp
(add-to-list 'find-file-not-found-functions #'help/create-non-existent-directory)
#+END_SRC

** File-system/directory management (Console)

You can use the usual machinery to work with the files. Highlight a region
and operation selections occur for all files in that region. Commands are
scheduled, and then executed, upon your command. Files can be viewed in modify
or read-only mode, too. There is an idea of =mark= in files, which is to select
them and perform operations on the marked files. There are helper methods for
most things you can think if like directories or modified-files or whatever,
meaning you can use regexen to mark whatever you like however you like. If that
suits you, then don't be afraid of using the regular expression builder
that is built into EMACS. Bulk marked file operations include additionally
copying, deleting, creating hard links to, renaming, modifying the mode,
owner, and group information, changing the time-stamp, listing the marked
files, compressing them, decrypting, verifying and signing, loading or byte
compiling them (Lisp files).

=g= updates the current buffer; =s= orders the listing by alpha or date-time.

=find-name-dired= beings the results back into Dired, which is nifty.

Wdired lets you modify files directly via the UI, which is interesting. Image-Dired
lets you do just that.

=+= creates a new directory. =dired-copy-filename-as-kill= stores the list of
files you have selected in the kill ring. =dired-compare-directories= lets you
perform all sorts of directory comparisons, a handy tool that you need once in
a while but definitely do need.
#+BEGIN_SRC emacs-lisp
(defun help/dired-copy-filename ()
  "Push the path and filename of the file under the point to the kill ring.
  Attribution: URL `https://lists.gnu.org/archive/html/help-gnu-emacs/2002-10/msg00556.html'"
  (interactive)
  (message "Added %s to kill ring" (kill-new (dired-get-filename))))
(defun help/dired-copy-path ()
  "Push the path of the directory under the point to the kill ring."
  (interactive)
  (message "Added %s to kill ring" (kill-new default-directory)))
(setq dired-listing-switches "-alh")
(setq dired-recursive-deletes 'top)
(use-package dired-details+
  :ensure t)
(setq-default dired-details-hidden-string "")
(defun help/dired-mode-hook-fn ()
  "Personal dired customizations."
  (local-set-key "c" 'help/dired-copy-filename)
  (local-set-key "]" 'help/dired-copy-path)
  (diff-hl-dired-mode)
  (load "dired-x")
  (turn-on-stripe-buffer-mode)
  (stripe-listify-buffer))
(add-hook #'dired-mode-hook #'help/dired-mode-hook-fn)
#+END_SRC

Try to guess the target directory for operations.
#+BEGIN_SRC emacs-lisp
(setq dired-dwim-target t)
#+END_SRC

Use EMACS =ls=.
#+BEGIN_SRC emacs-lisp
(help/on-osx
 (setq ls-lisp-use-insert-directory-program nil)
 (require 'ls-lisp))
#+END_SRC

After dabbling, something happened that really changed my mind. These three
articles changed everything: [fn:87e72370: http://www.masteringemacs.org/articles/2014/04/10/dired-shell-commands-find-xargs-replacement/] [fn:d82e40f9: http://www.masteringemacs.org/articles/2011/03/25/working-multiple-files-dired/] [fn:fe52afc4: http://www.masteringemacs.org/articles/2013/10/10/wdired-editable-dired-buffers/].
They just made the power of Dired so obvious, and so easy to use, that it
instantly because delightful to use. That was very, very cool. Even though I
was really, really happy with Finder and Explorer… suddenly it just became so
obvious and pleasant to use Dired. That is so wild.

Key notes when executing shell commands on file selection…

Substitution:
- =<cmd> ?= :: 1* calls to cmd, each file a single argument
- =<cmd> *= :: 1 call to =cmd=, selected list as argument
- =<cmd> *""= :: have the shell expand the * as a globbing wild-card
  - Not sure what this means

Synchronicity:
- =<cmd> …= :: by default commands are called synchronously
- =<cmd> &= :: execute in parallel
- =<cmd> ;= :: execute sequentially, asynchronously
- =<cmd> ;&= :: execute in parallel, asynchronously

Key notes on working with files in multiple directories… use the following:

Use =find= just like you would at the command line and all of the results show
up in a single Dired buffer that you may work with just like you would any other
file appearing in a Dired buffer. The abstraction here becomes so obvious, you
may ask yourself why you never considered such a thing /before/ now (as I did):
#+BEGIN_SRC emacs-lisp
(use-package find-dired
  :ensure t
  :config
  (setq find-ls-option '("-print0 | xargs -0 ls -ld" . "-ld")))
#+END_SRC

Noting that:
- =find-dired= :: is the general use case
- =find-name-dired= :: is for simple, single string cases

And if you want to use the faster Elisp version, that uses lisp regex, use:
- =find-lisp-find-dired= :: for anything
- =find-lisp-find-dired-subdirectories= :: for only directories

Key notes on working with editable buffers…

As the author notes, you probably already instinctually knew what is possible.
After reading his brief and concise exposition, it would be hard /not/ to
intuit what is possible! The options are big if you make a writable file buffer.
Think about using multiple cursors. Done? Well, that is a no-brainer. Once you
grok multiple cursors just =find-dired= what you need and then do what you need
to do to it. Very cool.

- =dired-toggle-read-only, C-x C-q= :: cycle between dired-mode and wdired-mode
- =wdired-finish-edit, C-c C-c= :: commit your changes
- =wdired-abort-changes, C-c ESC= :: revert your changes

#+BEGIN_SRC emacs-lisp
(use-package wdired
  :ensure t
  :config
  (setq wdired-allow-to-change-permissions t)
  (setq wdired-allow-to-redirect-links t)
  (setq wdired-use-interactive-rename t)
  (setq wdired-confirm-overwrite t)
  (setq wdired-use-dired-vertical-movement 'sometimes))
#+END_SRC

When you selected a bunch of files or directories, you /may/ want to communicate
somewhere your selection somehow. The simplest way to do this is to utilize
=dired-copy-filename-as-kill=. What a nice idea, and its default binding is =w=.

Since I started using a menu bar again, and wanting to get Imenu really
exercised, Dired in Imenu seems like an obvious choice.

#+BEGIN_SRC emacs-lisp
(use-package dired-imenu
  :ensure t)
#+END_SRC

** Finding Objects

Access nearly every object available in this system from one place.

#+BEGIN_SRC emacs-lisp
(require 'ido)
(use-package flx-ido
             :ensure t
             :config
             (ido-mode t))
(use-package ido-hacks
             :ensure t)
(use-package ido-ubiquitous
             :ensure t
             :config
             (ido-ubiquitous-mode t)
             (setq ido-create-new-buffer 'always)
             (flx-ido-mode t)
             (setq ido-use-faces nil))
(use-package ido-vertical-mode
             :ensure t
             :config
             (ido-vertical-mode t)
             (setq ido-vertical-define-keys 'C-n-C-p-up-down-left-right))
(global-set-key (kbd "s-x") #'ido-find-file)
(global-set-key (kbd "s-c") #'ido-switch-buffer)
#+END_SRC

Make functions search-able.

#+BEGIN_SRC emacs-lisp
(use-package smex
             :ensure t
             :config
             (smex-initialize)
             (global-set-key (kbd "s-v") #'smex))
#+END_SRC

Make URLs a first-class object.

#+BEGIN_SRC emacs-lisp
(setq ido-use-url-at-point t)
(setq ido-use-filename-at-point 'guess)
#+END_SRC

** Font

Use Unicode-Font to provide as many Unicode fonts as possible.

Here are the Unicode fonts that provide nearly everything.

| Name    | Version | URL | Comments                 |
|---------+---------+-----+--------------------------|
| [[http://sourceforge.net/projects/dejavu/files/dejavu/2.34/dejavu-fonts-ttf-2.34.tar.bz2][DejaVu]]  |    2.43 | [[http://sourceforge.net/projects/dejavu/files/dejavu/2.34/dejavu-fonts-ttf-2.34.tar.bz2][.]]   | Modern classic           |
| [[http://users.teilar.gr/~g1951d/][Symbola]] |    7.17 | [[http://users.teilar.gr/~g1951d/Symbola.zip][.]]   | Neat                     |
| [[http://www.quivira-font.com/][Quivira]] |     4.0 | [[http://www.quivira-font.com/files/Quivira.otf][.]]   | Amazing                  |
| [[https://code.google.com/p/noto/][Noto]]    |       ? | [[http://noto.googlecode.com/git/fonts/individual/hinted/NotoSans-Regular.ttc][1]] [[http://noto.googlecode.com/git/fonts/individual/unhinted/NotoSansSymbols-Regular.ttf][2]] | Has morse code, and more |

To test it run =view-hello-file= and =M-x list-charset-chars RET unicode-bmp RET=.

Perhaps educationally there is a character for bowel-movements: 💩.

#+BEGIN_SRC emacs-lisp
(use-package unicode-fonts
  :ensure t
  :config
  (unicode-fonts-setup))
#+END_SRC

Activate font locking everywhere possible.

#+BEGIN_SRC emacs-lisp
(global-font-lock-mode t)
#+END_SRC

Visualize ASCII values as their most likely Unicode representation.

#+BEGIN_SRC emacs-lisp
(use-package pretty-mode
  :ensure t
  :config
  (global-font-lock-mode t))
#+END_SRC

** Going to Objects

Go to any object in the frame quickly.

#+BEGIN_SRC emacs-lisp
(use-package avy
  :ensure t
  :config
  (key-chord-define-global "df" #'avy-goto-word-1)
  (key-chord-define-global "DF" #'avy-pop-mark))
#+END_SRC

** Grammar

#+BEGIN_SRC emacs-lisp
(use-package writegood-mode
  :ensure t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package langtool
  :ensure t
  :init
  (setq langtool-language-tool-jar (concat (getenv "EELIB") "/LanguageTool-2.8/languagetool-commandline.jar"))
  (setq langtool-mother-tongue "en")
  (setq langtool-java-bin (concat (getenv "JAVA_HOME") "/bin/java")))
#+END_SRC

** Intellisense (Auto Completion)

#+BEGIN_SRC emacs-lisp
(use-package fuzzy
  :ensure t)
(use-package auto-complete
  :ensure t
  :config
  (require 'auto-complete-config)
  (setq ac-quick-help-prefer-pos-tip nil)
  (ac-config-default)
  (setq ac-auto-start nil)
  (help/not-on-gui (ac-set-trigger-key "\t"))
  (help/on-gui (ac-set-trigger-key "<tab>"))
  (help/diminish #'auto-complete-mode))
(use-package auto-complete-chunk
  :ensure t)
#+END_SRC

Auto-completion for =.=-separated words.

#+BEGIN_SRC emacs-lisp
(use-package auto-complete-chunk
  :ensure t)
#+END_SRC

** Macros

The macro recorder and Multiple-Cursors provide two ways to do the right thing
in different situations.

#+BEGIN_SRC emacs-lisp
(use-package multiple-cursors
  :ensure t
  :config
  (global-set-key (kbd "s-4") #'mc/mark-next-like-this)
  (global-set-key (kbd "s-3") #'mc/mark-previous-like-this)
  (global-set-key (kbd "s-2") #'mc/mark-all-like-this)
  (global-set-key (kbd "s-1") #'mc/edit-lines))
#+END_SRC

** Mark and Region

When you start typing and text is selected, replace it with what you are typing,
or pasting

#+BEGIN_SRC emacs-lisp
(delete-selection-mode t)
#+END_SRC

** Minibuffer

Make it easier to answer questions.
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Comfortably display information.
#+BEGIN_SRC emacs-lisp
(setq resize-mini-windows t)
(setq max-mini-window-height 0.33)
#+END_SRC

Allow recursive commands-in-commands and highlight the levels of recursion.
#+BEGIN_SRC emacs-lisp
(setq enable-recursive-minibuffers t)
(minibuffer-depth-indicate-mode t)
#+END_SRC

** Mouse

Scroll pleasantly with the mouse wheel. A slow turn moves the buffer up and down
one line at a time. So does a fast turn. Anything further than 5-10 lines deserves
a fast navigation vehicle.

#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
(setq mouse-wheel-progressive-speed nil)
(setq mouse-wheel-follow-mouse t)
#+END_SRC

** Occur

#+BEGIN_SRC emacs-lisp
(defun help/occur-mode-hook-fn ()
  "Personal customizations."
  (interactive)
  (turn-on-stripe-buffer-mode)
  (stripe-listify-buffer))
(add-hook #'occur-mode-hook #'help/occur-mode-hook-fn)
#+END_SRC

** Popups

Provide more style options for popups.

#+BEGIN_SRC emacs-lisp
(use-package pos-tip
             :ensure t)
(help/on-windows
 (ignore-errors
   (pos-tip-w32-max-width-height)))
#+END_SRC

Make the colors more pleasant.

#+BEGIN_SRC emacs-lisp
(setq pos-tip-foreground-color "#073642")
(setq pos-tip-background-color "#839496")
#+END_SRC

Provide popup notifications.

#+BEGIN_SRC emacs-lisp
(use-package alert
  :ensure t
  :config
  (setq alert-fade-time 10)
  (help/on-gui
   (help/on-osx
    (setq alert-default-style 'growl)))
  (setq alert-reveal-idle-time 120))
#+END_SRC

** Projects

Directories that have Git working copies are logically projects. Manage them
with Projectile.

#+BEGIN_SRC emacs-lisp
(use-package projectile :if nil
             :ensure t
             :config
             (projectile-global-mode t)
             (key-chord-define-global "s-z" #'projectile-find-file)
             (help/diminish "projectile-mode")
             (gcr/on-windows
              (setq projectile-indexing-method 'alien)))
#+END_SRC

Notify Magit about every working copy that Projectile knows about.

#+BEGIN_SRC emacs-lisp
(eval-after-load "projectile"
  '(progn (setq magit-repository-directories (mapcar (lambda (dir)
                                                       (substring dir 0 -1))
                                                     (remove-if-not (lambda (project)
                                                                      (file-directory-p (concat project "/.git/")))
                                                                    (projectile-relevant-known-projects)))

                magit-repository-directories-depth 1)))
#+END_SRC

** Replacing

Display information about search-and-or-replace operation.

#+BEGIN_SRC emacs-lisp
(use-package anzu
             :ensure t
             :config
             (global-anzu-mode t)
             (global-set-key (kbd "M-%") 'anzu-query-replace)
             (global-set-key (kbd "C-M-%") 'anzu-query-replace-regexp)
             (setq anzu-mode-lighter "")
             (setq anzu-deactivate-region t)
             (setq anzu-search-threshold 1000)
             (setq anzu-replace-to-string-separator " => "))
#+END_SRC

** Save History of All Things

It is nice to have commands and their history saved so that every time you get
back to work, you can just re-run stuff as you need it.

#+BEGIN_SRC emacs-lisp
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring))
(savehist-mode t)
#+END_SRC

** Searching

When searching allow a space to many any number.

#+BEGIN_SRC emacs-lisp
(setq isearch-lax-whitespace t)
(setq isearch-regexp-lax-whitespace t)
#+END_SRC

Make searches case-insensitive.

#+BEGIN_SRC emacs-lisp
(setq-default case-fold-search t)
#+END_SRC

** Spell Checking

Ispell is simple and powerful.

*** Org-Mode

Never ispell the following objects.

Source-Blocks.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("^#\\+begin_src ". "#\\+#+end_src$"))
(add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_SRC ". "#\\+#+END_SRC$"))
#+END_SRC

Example-Blocks. This system often uses Source-Blocks to edit content and
Example-Blocks to make it easily renderable when it is not for running.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("^#\\+begin_example ". "#\\+end_example$"))
(add-to-list 'ispell-skip-region-alist '("^#\\+BEGIN_EXAMPLE ". "#\\+END_EXAMPLE$"))
#+END_SRC

Properties.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("\:PROPERTIES\:$" . "\:END\:$"))
#+END_SRC

Footnotes.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("\\[fn:.+:" . "\\]"))
#+END_SRC

Footnotes with URLs that contain line-breaks.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("^http" . "\\]"))
#+END_SRC

Verbatim

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("=.*" . ".*="))
#+END_SRC

Bold text list items.

#+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '("- \\*.+" . ".*\\*: "))
#+END_SRC

Export properties.

#+BEGIN_SRC emacs-lisp
(defun help/ispell-org-header-lines-regexp (h)
  "Help ispell ignore org header lines."
  (interactive)
  (cons (concat "^#\\+" h ":") ".$"))

(defun help/ispell-a2isra (block-def)
  "Add to the ispell skip region alist the BLOCK-DEF."
  (interactive)
  (add-to-list 'ispell-skip-region-alist block-def))

(let (void)
  (--each
      '("ATTR_LATEX"
        "AUTHOR"
        "CREATOR"
        "DATE"
        "DESCRIPTION"
        "EMAIL"
        "EXCLUDE_TAGS"
        "HTML_CONTAINER"
        "HTML_DOCTYPE"
        "HTML_HEAD"
        "HTML_HEAD_EXTRA"
        "HTML_LINK_HOME"
        "HTML_LINK_UP"
        "HTML_MATHJAX"
        "INFOJS_OPT"
        "KEYWORDS"
        "LANGUAGE"
        "LATEX_CLASS"
        "LATEX_CLASS_OPTIONS"
        "LATEX_HEADER"
        "LATEX_HEADER_EXTRA"
        "OPTIONS"
        "SELECT_TAGS"
        "STARTUP"
        "TITLE")
    (help/ispell-a2isra (help/ispell-org-header-lines-regexp it))))
#+END_SRC

** Sudo

Configure Sudo with Ido.

#+BEGIN_SRC emacs-lisp
(help/on-osx
 (defun help/ido-find-file (&rest args)
   "Find file as root if necessary.

Attribution: SRC `http://emacsredux.com/blog/2013/04/21/edit-files-as-root/'"
   (unless (and buffer-file-name
              (file-writable-p buffer-file-name))
     (find-alternate-file (concat "/sudo:root@localhost:" buffer-file-name))))

 (advice-add 'ido-find-file :after #'help/ido-find-file))
#+END_SRC

** Syntax Checking

Perform syntactic analysis all the time.

#+BEGIN_SRC emacs-lisp
(use-package flycheck :if nil
             :ensure t
             :config
             (add-hook 'after-init-hook #'global-flycheck-mode)
             (help/diminish "flycheck-mode"))
#+END_SRC

** Templating

#+BEGIN_SRC emacs-lisp
(use-package yasnippet
             :ensure t
             :config
             (yas-global-mode t)
             (help/diminish #'yas-minor-mode)
             (defun help/yas-minor-mode-hook-fn ()
               "Personal customizations."
               (define-key yas-minor-mode-map (kbd "<tab>") nil)
               (define-key yas-minor-mode-map (kbd "TAB") nil)
               (define-key yas-minor-mode-map (kbd "s-5") 'yas-expand))
             (add-hook #'yas-minor-mode-hook #'help/yas-minor-mode-hook-fn))
#+END_SRC

** Version Control

Use Magit for Git.

#+BEGIN_SRC emacs-lisp
(use-package magit
             :ensure t
             :config
             (global-set-key (kbd "s-e") #'help/safb-magit-status))
#+END_SRC

Leave the VC message template empty.

#+BEGIN_SRC emacs-lisp
(eval-after-load 'log-edit
  '(remove-hook 'log-edit-hook 'log-edit-insert-message-template))
#+END_SRC

Git ignore files are text files.

#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '(".gitignore$" . text-mode))
#+END_SRC

** Whitespace Management

Make control characters easily visible.

#+BEGIN_SRC emacs-lisp
(use-package whitespace :if nil
             :ensure t
             :config
             (setq whitespace-style '(trailing lines tab-mark))
             (setq whitespace-line-column 80)
             (global-whitespace-mode 1)
             (help/diminish "global-whitespace-mode")
             (help/diminish "whitespace-mode"))
#+END_SRC

* Quiet and Pleasant Appearance
   :PROPERTIES:
   :noweb-ref: Quiet-and-Pleasant-Appearance
   :END:

Configure EMACS to personal-taste for "noise" and "form".

** Buffer

In practice ~text-mode~ and ~prog-mode~ have common preferencess for this system.
The EMACS literature advises that modes extend one of them. That makes it easier
to configure basically everything using ~prog-mode-hook~. In practice the latter
is too new. Not all programming modes inherit from it. Not even IELM is ready.
With that in mind this system:

- Defines common configuration here for reuse in every desired mode.
- Configures each mode that want's to use it explicitly instead of relying on
  inheriting from ~prog-mode~.

- Line numbers make documents easier to read.
- Indicate that Text-Mode buffers ought to be 80 characters wide.
#+BEGIN_SRC emacs-lisp
(use-package fill-column-indicator
  :ensure t
  :config
  (setq-default fill-column 80))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun help/text-prog*-setup ()
  "HELP's standard configuration for buffer's working with text, often for
   programming."
  (interactive)
  (linum-mode)
  (fci-mode))

(add-hook #'text-mode-hook #'help/text-prog*-setup)
#+END_SRC

Give buffers backed by identically named files distinguishable names.

#+BEGIN_SRC emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+END_SRC

Don't use audible bells, use visual bells.

#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore)
(setq visible-bell t)
#+END_SRC

Highlight s-expressions.

#+BEGIN_SRC emacs-lisp
(setq blink-matching-paren nil)
(show-paren-mode)
(setq show-paren-delay 0)
(setq show-paren-style 'expression)
#+END_SRC

The cursor should not blink and distract you. On a graphic display make the
cursor a box and stretch it as wide as the character below it.

#+BEGIN_SRC emacs-lisp
(blink-cursor-mode 0)
(help/on-gui
 (setq-default cursor-type 'box)
 (setq x-stretch-cursor 1))
#+END_SRC

EMACS used UTF-8 by default. Make copying and pasting easier.

#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
(help/on-gui
 (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
 (help/on-windows
  (set-clipboard-coding-system 'utf-16le-dos)))
#+END_SRC

Make it very easy to see the line with the cursor.

#+BEGIN_SRC emacs-lisp
(global-hl-line-mode t)
#+END_SRC

** Color Theme

The Solarized theme is the perfect theme for everything. bozhidar's
release. It is soft and gentle yet easy to read in any situation.

#+BEGIN_SRC emacs-lisp
(use-package solarized-theme
  :ensure t
  :config
  (setq solarized-distinct-fringe-background t)
  (setq solarized-high-contrast-mode-line t)
  (setq solarized-use-less-bold t)
  (setq solarized-use-more-italic nil)
  (setq solarized-emphasize-indicators nil)
  (load-theme 'solarized-dark))
#+END_SRC

** Comint

=comint-mode= is only maybe the second most important thing for making Emacs
really, really special.

#+begin_src emacs-lisp
(setq comint-scroll-to-bottom-on-input 'this)
(setq comint-scroll-to-bottom-on-output 'others)
(setq comint-move-point-for-output 'others)
(setq comint-show-maximum-output t)
(setq comint-scroll-show-maximum-output t)
(setq comint-move-point-for-output t)
#+end_src

This configuration had been working fine for a long time. The intent was for it
to be crystal clear that the prompt line in comint buffers would be read only.
This turned out to be a mistake; though I am not sure why, when, or how it
became a mistake. Nonetheless, this should be left alone. The way the issue here
manifested was that all ℝ buffers opened by =ess= were 100% read only which
obviously is a *big issue* if you actually want to use! ROFL

#+BEGIN_SRC emacs-lisp
(setq comint-prompt-read-only nil)
#+END_SRC

** Font

The best programming font is Deja Vu Sans Mono because it sans-serif and
support a lot of Unicode characters. Set it to a good default for an 80
character wide buffer and make it easy to adjust it.

#+BEGIN_SRC emacs-lisp
(help/on-gui
 (defvar help/font-size 10 "The preferred font size.")
 (help/on-osx (setq help/font-size 17))
 (help/on-windows (setq gcr/font-size 13))
 (defconst help/font-base "DejaVu Sans Mono" "The preferred font name.")
 (defun help/font-ok-p ()
   "Is the configured font valid?"
   (interactive)
   (member help/font-base (font-family-list)))
 (defun help/font-name ()
   "Compute the font name and size string."
   (interactive)
   (let* ((size (number-to-string help/font-size))
          (name (concat help/font-base "-" size)))
     name))
 (defun help/update-font ()
   "Updates the current font given configuration values."
   (interactive)
   (if (help/font-ok-p)
       (progn
         (message "Setting font to: %s" (help/font-name))
         (set-default-font (help/font-name)))
     (message (concat "Your preferred font is not available: " help/font-base))))
 (defun help/text-scale-increase ()
   "Increase font size"
   (interactive)
   (setq help/font-size (+ help/font-size 1))
   (help/update-font))
 (defun help/text-scale-decrease ()
   "Reduce font size."
   (interactive)
   (when (> help/font-size 1)
     (setq help/font-size (- help/font-size 1))
     (help/update-font)))
 (help/update-font))
#+END_SRC

** Frame

The scroll-bars are helpful for new users.

#+BEGIN_SRC emacs-lisp
(scroll-bar-mode 0)
#+END_SRC

The tool-bar is helpful for new users. Isn't the argument funny?

#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC

** Help

Display it, learn what you wish, and move on by closing the buffer.

#+BEGIN_SRC emacs-lisp
(setq help-window-select t)
#+END_SRC

** Pointer

Hide the pointer when typing.

#+BEGIN_SRC emacs-lisp
(setq make-pointer-invisible t)
#+END_SRC

** Version Control

Provide VC file status indicators.

#+BEGIN_SRC emacs-lisp
(use-package diff-hl
  :ensure t)
#+END_SRC

** Window

Menu bars make EMACS more accessible to non-EMACS users.

#+BEGIN_SRC emacs-lisp
(menu-bar-mode t)
#+END_SRC

Easily return to previous configurations.

#+BEGIN_SRC emacs-lisp
(winner-mode t)
#+END_SRC

* Principle of Least Astonishment (POLA)
  :PROPERTIES:
  :noweb-ref: Principle-of-Least-Astonishment
  :END:

EMACS can load 3 different representations of a Emacs-Lisp source file code
OOTB. The name of source code file is the value before the file extension. When
you pass ~load~ a name it searches for an acceptable representation. Representation
types are indicated by their extension name. =.el= is a human readable and
uncompiled. =.elc= is not human readable and compiled. =.gz= is Gzip compressed and
contains =.el= or =.elc= files.

The variable ~load-suffixes~ determines the order for which text and byte-code
representations are first searched by extension-name. The variable
~load-file-rep-suffixes~ determines the order for all other extension types.

OOTB, EMACS combines the productivity of REPL style of development with the
speed of compiled code by ~load~'ing byte-code first, text second, and compressed
third. This workflow gives you the fastest code at run-time and lets you
experiment with new features stored in text. When you are ready to use them
every time, you compile them. There is only one downside of this approach: when
you forget that it works this way it can be confusing.

When you forget about that style of system you end up with surprising behavior.
The surprise comes when you forget to compile code and then write new code that
depends on the now old version of that code. After the next build, your system
can break in surprising ways. This violates the Principle of Least Astonishment.

This system values predictability so it does the simplest thing possible: ~load~
searches for the newest representation of a file and uses that one. It assumes
that Sysop has total and complete control over the management of file
representations.

This is the *first* thing that /ought/ to happen in the initialization of *any*
tangled system.

#+BEGIN_SRC emacs-lisp
(setq load-prefer-newer t)
#+END_SRC

* Watch What You Eat
  :PROPERTIES:
  :noweb-ref: Watch-What-You-Eat
  :END:

*Code requiring package-management can only follow this block.*

Before ELPA, I used SVN to manage software packages for EMACS. After ELPA,
I used ELPA-packages. Now this system uses MELPA and GNU. MELPA packages always
have their issues fixed very quickly. GNU packages rarely have issues.

Initialize Package.

#+BEGIN_SRC emacs-lisp
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/") t)
#+END_SRC

Use-Package is the most configurable and performant way to manage ELPA packages.

Add the Use-Package distribution the load path.

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/use-package")
#+END_SRC

Load Use-Package.

#+BEGIN_SRC emacs-lisp
(require 'use-package)
#+END_SRC

* Style Guide

- Code Block
  - Tell the story in speech, and then in code.
  - Consider it another paragraph and indent appropriately.
  - When contained within a list.
    - Indent begin/end blocks with list content; this makes it clear to Org-Mode
      to export it as a code block.
    - Source code is indented according to existing settings. This system keeps
      it left-aligned, saving space.
- Content
  - When importing, update to conform with Style-Guide.
- Dictionary
  - Exemple Complet Minimal (ECM) :: The minimal complete example of expected
    versus actual behavior. Comes from the [[http://orgmode.org/worg/org-faq.html][Org-Mode]] community.
  - Key-Bind :: A verb. The act of creating a Key Binding.
  - Out of the Box (OOTB) :: The default configuration of something.
  - Sysop :: A proper noun. The System-Operator. The human operating this EMACS
    based Org-Mode enabled literate programming system. The reader.
  - Tangle :: A verb. Assemble a document for consumption by another program or
    machine.
  - Weave :: A verb. Prepare a document for consumption by a human.
- Formatting
  - Code Snippet.
    - Programming language expressions.
    - Use ~code style~.
  - Non-Code Snippet.
    - Program names, file types
    - Use =verbatim= style
  - Package.
    - Same as Headline.
    - Dashes separate definition.
    - Acronyms are all upper case to distinguish from words for example "GNU"
      vs "Gnu".
- Headline.
  - Capitalize nouns, verbs, and adjectives.
  - Don't capitalize conjunctions unless they are starting the definition.
  - Sell this "chapter" to the reader.
- Hyperlink.
  - External.
    - Exclude those easily found with a search-engine unless you are willing to
      verify their existence frequently.
    - Include when they make the task at hand immensely easier.
  - Internal.
    - Heading artifacts can be referenced so the need here is minimal to
      non-existent.
- Literate Programming.
  - Comments.
    - Exclude from tangle-blocks and rely on source-block for traceability.
  - Noweb-Ref.
    - Same as Headline.
    - Replace spaces with dashes.
    - Probably the Heading name.
    - Keep depth shallow
- Maintenance.
  - Frequently check spelling, grammar, and weasel-words.
- Plain List.
  - End single sentences with a period.
- Programming Language.
  - Emacs-Lisp.
    - Use ~t~ for ~true~.
    - Almost always use ~defun~ instead of ~advice-add~.
      - Functions are more normal and predictable.
      - Advice can subtly break without you noticing.
    - Paramemter.
      - ~nil~ for =FALSE=.
      - ~t~ for =TRUE=.
      - ~n~ for numerical values.
- Tangling.
  - When ordering matters, rely on block-reuse to enforce correct generation.
- Voice.
  - Provide answers; do not pose questions or observations.
  - Simple and detailed.
  - Pleasant conversation style.
  - Audience is Sysop; the author included.
- Word Choice.
  - Use Arabic numerals.
  - Instead of writing "tells EMACS", communicate the result.
  - "EMACS" refers to this software.
  - "This system" refers to this configuration of EMACS.

* Hacking

** Common
  :PROPERTIES:
  :noweb-ref: Hacking-Common
  :END:

Common configuration definitions.

*** Hooks

- Hacking mode hooks.
  - Configurations common to every hacking vehicle.
    #+BEGIN_SRC emacs-lisp
(setq help/hack-modes '())
    #+END_SRC
  - LISP mode hooks.
    - Are hacking modes.
      #+BEGIN_SRC emacs-lisp
(setq help/hack-lisp-modes
      '(emacs-lisp-mode-hook
	ielm-mode-hook
	lisp-interaction-mode))
(setq help/hack-modes (append help/hack-modes help/hack-lisp-modes))
      #+END_SRC
    - IELM mode hook.
      - Does one or two more things.

***  Hook Functions

- Use the standard ~help/text-prog*-setup~.
- Indent at every opportunity and automatically. Verify that it makes sense
  for the mode. Explicitly define instead of relying on ~prog-mode~ inheritance.
  #+BEGIN_SRC emacs-lisp
(use-package aggressive-indent
  :ensure t
  :config)
  #+END_SRC
- Always maintain balanced brackets. Easily wrap the selected region. Auto-escape
  strings pasted into other strings.
  #+BEGIN_SRC emacs-lisp
(use-package smartparens :if nil
  :ensure t
  :config
  (require 'smartparens-config)
  (setq sp-show-pair-from-inside nil)
  (smartparens-global-strict-mode)
  (help/diminish "smartparens-mode"))
  #+END_SRC
- Implementation.
 #+BEGIN_SRC emacs-lisp
(defun help/hack-common-mode-hook-fn ()
  (interactive)
  (help/text-prog*-setup)
  (smartparens-strict-mode)
  (aggressive-indent-mode))
#+END_SRC

*** Wiring

 #+BEGIN_SRC emacs-lisp
(let (void)
  (--each help/hack-modes
    (add-hook it #'help/hack-common-mode-hook-fn)))

(let (void)
  (--each help/hack-lisp-modes
    (add-hook it #'help/emacs-lisp-mode-hook-fn)))

(add-hook #'ielm-mode-hook #'help/ielm-mode-hook)
 #+END_SRC

** Emacs Lisp
  :PROPERTIES:
  :noweb-ref: Hacking-Emacs-Lisp
  :END:

#+BEGIN_SRC emacs-lisp
(setq initial-scratch-message nil)
(require 'lexbind-mode)

(defun help/elisp-eval-buffer ()
  "Intelligently evaluate an Elisp buffer."
  (interactive)
  (help/save-all-file-buffers)
  (eval-buffer))

(defun endless/sharp ()
  "Insert #' unless in a string or comment.

RC: URL `http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html?source=rss'"
  (interactive)
  (call-interactively #'self-insert-command)
  (let ((ppss (syntax-ppss)))
    (unless (or (elt ppss 3)
		(elt ppss 4))
      (insert "'"))))

(defun help/elisp-mode-local-bindings ()
  "Helpful behavior for Elisp buffers."
  (local-set-key (kbd "s-l eb") 'help/elisp-eval-buffer)
  (local-set-key (kbd "s-l ep") 'eval-print-last-sexp)
  (local-set-key (kbd "s-l td") 'toggle-debug-on-error)
  (local-set-key (kbd "s-l mef") 'macroexpand)
  (local-set-key (kbd "s-l mea") 'macroexpand-all)
  (local-set-key (kbd "s-p") 'help/describe-thing-in-popup)
  (local-set-key (kbd "s-:") 'my-eval-expression)
  (local-set-key (kbd "#") 'endless/sharp))

(defun help/emacs-lisp-mode-hook-fn ()
  (interactive)
  (help/elisp-mode-local-bindings)
  (lexbind-mode)
  (turn-on-eldoc-mode)
  (help/diminish 'eldoc-mode))

(setq ielm-noisy nil)

(setq ielm-prompt "𝔼LISP> ")

(setq ielm-dynamic-return nil)

(setq ielm-dynamic-multiline-inputs nil)

(defun help/ielm-mode-hook-fn ()
  "Personal customizations."
  (interactive)
  (help/ielm-auto-complete))
#+END_SRC

** Org-Mode
  :PROPERTIES:
  :noweb-ref: Hacking-Org-Mode
  :END:

When source blocks are evaluated, their results get stored in a result area,
typically for display. If the results are small, they are displayed with colons
instead of an =example= block. Instead, *always* place them in an
example block. This makes exports more consistent and other Org-Mode features seem
to behave more predictably.

#+BEGIN_SRC emacs-lisp
(setq org-babel-min-lines-for-block-output 0)
#+END_SRC

Use Yasnippets.

#+BEGIN_SRC emacs-lisp
(add-to-list #'yas-snippet-dirs "~/src/yasnippet-org-mode")
(yas-reload-all)
#+END_SRC

When Source-Block evaluation results are inserted try to use the name or cache-id.
If neither are present, the =RESULTS= block becomes a =NAME= "results" block.

#+BEGIN_SRC emacs-lisp
(setq org-babel-results-keyword "NAME")
#+END_SRC

Configure Org-Mode to manage it's Source-Block backed buffers the same as the
rest of this system.

#+BEGIN_SRC emacs-lisp
(setq org-edit-src-auto-save-idle-delay 0)
(setq org-edit-src-turn-on-auto-save nil)
#+END_SRC

Update in-buffer images after Source-Block execution. This is a programming task.
That is why it is under this heading and Evaluation. This is a setting configuring
how the results of evaluation are refreshed in EMACS.

#+BEGIN_SRC emacs-lisp
(defun help/org-babel-after-execute-hook ()
  "Personal settings for the `org-babel-after-execute-hook'.

This does not interfere with exports.

Attribution: URL `https://lists.gnu.org/archive/html/emacs-orgmode/2015-01/msg00534.html'"
  (interactive)
  (org-redisplay-inline-images))

(add-hook 'org-babel-after-execute-hook 'help/org-babel-after-execute-hook)
#+END_SRC

Never "automatically" evaluate a source block.

#+BEGIN_SRC emacs-lisp
(setq org-confirm-babel-evaluate nil)
#+END_SRC

Make it unpleasant for Sysop to modify source-block outside of a source-block
backed buffer. The next step is to write some code to prevent modifying
source-blocks outside of that place.

#+BEGIN_SRC emacs-lisp
(setq org-src-tab-acts-natively nil)
#+END_SRC

My personal TODO workflow.

#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO" "IN-PROGRESS" "BLOCKED" "REVIEW" "DONE")))
#+END_SRC

When running in a GUI, I would like linked images to be displayed inside of
Emacs.

#+BEGIN_SRC emacs-lisp
(setq org-startup-with-inline-images (display-graphic-p))
#+END_SRC

Use Ido completion in Org-Mode.

#+BEGIN_SRC emacs-lisp
(setq org-completion-use-ido t)
(setq org-outline-path-complete-in-steps nil)
(setq org-completion-use-iswitchb nil)
#+END_SRC

Org-Mode lets you use single letter commands to do stuff on headers. I like to
use =c= for cycling the header expansion.

#+BEGIN_SRC emacs-lisp
(setq org-use-speed-commands t)
#+END_SRC

Ask before execution of shell links. This might seem like an Evaluation
activity. It is. It is interactive.

#+BEGIN_SRC emacs-lisp
(setq org-confirm-shell-link-function 'y-or-n-p)
#+END_SRC

Ask before execution of Emacs-Lisp.

#+BEGIN_SRC emacs-lisp
(setq org-confirm-elisp-link-function 'y-or-n-p)
#+END_SRC

Make sure that incomplete TODO entries prevent the enclosing parent from every
turning to DONE.

#+BEGIN_SRC emacs-lisp
(setq org-enforce-todo-dependencies t)
#+END_SRC

Allow the mouse to do Org-Mode things like expand and collapse headings.

#+BEGIN_SRC emacs-lisp
(when (display-graphic-p)
  (require 'org-mouse))
#+END_SRC

Use a real ellipsis to render an ellipsis for Org-Mode stuff like showing that a
header is collapsed.

#+BEGIN_SRC emacs-lisp
(setq org-ellipsis "…")
#+END_SRC

It is easy to see indentation of headlines without having to count asterisks, so
don't show them, only show the significant and last one.

#+BEGIN_SRC emacs-lisp
(setq org-hide-leading-stars t)
#+END_SRC

Display emphasized text as you would in a WYSIWYG editor.

#+BEGIN_SRC emacs-lisp
(setq org-fontify-emphasized-text t)
#+END_SRC

Use Unicode characters to visualize things like right arrow eg \rarr . Most of those
symbols are correctly exported to the destination format. The most obvious is
this example in LaTeX versus Text.

#+BEGIN_SRC emacs-lisp
(setq org-pretty-entities t)
#+END_SRC

Highlight LaTeX and related markup.

Normally, I don't do any syntax highlighting, as I believe that should be
delegated to source buffers, thinking that to do otherwise is distracting.
However, I already do configure subscripts and Greek letters to be displayed
with syntax highlighting, because I want to indicate to the human reader that
they are special, and specifically /not/-Unicode. Do the same thing for LaTeX
and related markup.

#+BEGIN_SRC emacs-lisp
(setq org-highlight-latex-and-related '(latex script entities))
#+END_SRC

Allow "refactoring" of Footnotes between documents.

#+BEGIN_SRC emacs-lisp
(setq org-footnote-define-inline t)
(setq org-footnote-auto-label 'random)
(setq org-footnote-auto-adjust nil)
(setq org-footnote-section nil)
#+END_SRC

This is an amazingly easy way to screw up your document. The more you edit
org docs, the more you realize how you must truly protect it.

#+BEGIN_SRC emacs-lisp
(setq org-catch-invisible-edits 'error)
#+END_SRC

Though I am not delving deep, it is hard not to want to customize some stuff
and perhaps this is the start. Even though I enabled this, I don't think that I
ever used it.

#+BEGIN_SRC emacs-lisp
(setq org-loop-over-headlines-in-active-region t)
#+END_SRC

It is /almost always/ faster to work with org documents when they are fully
expanded. Anyway, the structure cycling makes it really, really easy to get an
/outline view/ again.

#+BEGIN_SRC emacs-lisp
(setq org-startup-folded "nofold")
#+END_SRC

When images are displayed in the buffer, display them in their actual size. As
the operator, I want to know their true form. Any modifications required for
export will be stated explicitly.

#+BEGIN_SRC emacs-lisp
(setq org-image-actual-width t)
#+END_SRC

Hide the delimeter for emphasized text. Unicode characters break table
alignment.

#+BEGIN_SRC emacs-lisp
(setq org-hide-emphasis-markers t)
#+END_SRC

Realign tables automatically.

#+BEGIN_SRC emacs-lisp
(setq org-startup-align-all-tables t)
#+END_SRC

Always use Unicode checkboxes.

#+BEGIN_SRC emacs-lisp
(setq org-html-checkbox-type 'unicode)
#+END_SRC

You may display syntax highlighting for code in source blocks. I don't.

#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively nil)
#+END_SRC

Never indent the contents of a source-block automatically.

#+BEGIN_SRC emacs-lisp
(setq org-edit-src-content-indentation 0)
#+END_SRC

When edit mode is exited, the option exists to automatically remove empty
opening and closed lines for the source block. Never do this. The thing is that
I forgot why. When I was working on a recent analysis with ℝ there was a
space appearing in the opening and closing line of the source block that didn't
appear in the source editing buffer. That surprised me. I am sure that I've
forgotten why this is the case. I don't like it because you add a bunch of
empty lines in the source buffer for every source block. With that in mind I
will enable this feature and try it out again.

#+BEGIN_SRC emacs-lisp
(setq org-src-strip-leading-and-trailing-blank-lines t)
#+END_SRC

The source block buffer may be configured to appear in a few different places.
For a while I really liked =reorganize-frame= because sometimes you want to be
able to see the code you are editing in edition to the rest of the document. At
least that is what I am telling myself. Once I learned you could change it I
realized that 1 I should have asked if it could be changed and 2 I should have
changed it. The flow that I've got configured here is that you are either in the
source document where code blocks are not highlighted or you are in the source
block so you are editing in a buffer that is full-fledged ALEC. That is the best
way so you can focus completely on each task at hand in the ideal mode for that
task. Anything else results in distractions and errors.

#+BEGIN_SRC emacs-lisp
(setq org-src-window-setup 'current-window)
#+END_SRC

Org-Mode has a really nice feature that hitting =C-c C-c= will generally just do
the /right thing/. It is really nice. That feature extends to source blocks of
course. Ironically I had a typo here, typing /of curse/ instead of /of course/.
The thing is that you really, really need to develop a personal workflow, and
then configure the tool to enable it. The more I learn about Org-Mode, the more
leery I am about making it really easy to evaluate code. I want it to be a
really, really specific and decided action to evaluate a code block, so don't
make it so easy as =C-c C-c=.

#+BEGIN_SRC emacs-lisp
(setq org-babel-no-eval-on-ctrl-c-ctrl-c t)
#+END_SRC

Promimently display the source-block's name if it has one.

#+BEGIN_SRC emacs-lisp
(defun help/org-edit-src-code-plus-name ()
  "Edit the well-described source code block.

Attribution: URL `https://lists.gnu.org/archive/html/emacs-orgmode/2014-09/msg00778.html'

Attribtion: URL `http://emacs.stackexchange.com/a/8168/341'"
  (interactive)
  (let* ((eop  (org-element-at-point))
         (name (or (org-element-property :name (org-element-context eop))
                  "ॐ"))
         (lang (org-element-property :language eop))
         (buff-name (concat "*Org Src " name "[" lang "]*"))
         (file-name (buffer-file-name)))
    (org-edit-src-code nil buff-name)
    (setq buffer-file-name file-name)))
#+END_SRC

Configure the system to successfully use ~vc-next-action~ while editing a
Source-Block. Before perfoming the edit, check if it is Org-Mode and
exit the Source-Block Buffer (SBB). If this system stays in the SBB
when calling ~vc-next-action~ the entire contents of the buffer are escaped
as Org-Mode source code upon returning to the source buffer (this).

#+BEGIN_SRC emacs-lisp
(defun help/vc-next-action ()
  "If in org source block, exit it before `vc-next-action'."
  (interactive)
  (when (condition-case nil
            (org-src-in-org-buffer)
          (error nil))
    (org-edit-src-exit))
  (vc-next-action nil))
#+END_SRC

Never use the original version.

#+BEGIN_SRC emacs-lisp
(setq org-edit-src-code nil)
#+END_SRC

*** Keybindings

Started questioning why after hitting RETURN while in lists I have to hit TAB to
get indented properly. Kind of a dead giveaway that I should be
return-and-indenting! Looked at =org-return= to find that it has an argument
about indenting and then saw that =org-return-indent= passes it for you. With that
in mind, RETURN is bound to that now. Now ALEC has four different kinds of
"returns" in Org in order of likelihood of usage:

- org-return-indent :: Make it really easy to work in existing list items,
  headings, and tables
  - This is listed first because I often go back to modify entries
  - <return> because it is used the most
- org-meta-return :: Make it really easy to add new list items, headings, and
  table contents
  - M-<return> because the binding comes with Org
- electric-indent-just-newline :: For when I want to break out of the default
  Org indentation to start working at the beginning of the line for example when
  I'm done working in a list or have just created a new heading
  - C-M-<return> because it is next step "lower" in the binding
- help/smart-open-line :: When I want to insert a new line between the current
  and next line then position the cursor correctly indented at the start of it.
  - s-<return> because it is that is the last place in the modifier key chain

#+BEGIN_SRC emacs-lisp
(help/not-on-gui
 (define-key org-mode-map (kbd "RET") 'org-return-indent)
 (define-key org-mode-map (kbd "C-M-RET") 'electric-indent-just-newline))
(help/on-gui
 (define-key org-mode-map (kbd "<return>") 'org-return-indent)
 (define-key org-mode-map (kbd "C-M-<return>") 'electric-indent-just-newline))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(define-key org-mode-map (kbd "s-j") #'org-babel-next-src-block)
(define-key org-mode-map (kbd "s-k") #'org-babel-previous-src-block)
(define-key org-mode-map (kbd "s-i") #'help/safb-org-babel-tangle)
(define-key org-mode-map (kbd "s-l") #'help/org-edit-src-code-plus-name)
(define-key org-mode-map (kbd "s-o") #'org-babel-execute-maybe)
(define-key org-mode-map (kbd "s-;") #'org-babel-view-src-block-info)
(define-key org-mode-map (kbd "s-p") #'org-babel-demarcate-block)
#+END_SRC

Make =s-l= do the same thing to leave the Source-Block-Buffer.

#+BEGIN_SRC emacs-lisp
(define-key org-src-mode-map (kbd "s-l") #'org-edit-src-exit)
#+END_SRC

** Structured Query Language (SQL)
