#+PROPERTY: header-args :tangle "./.org-mode-org2blog.emacs.el" :results output silent

* Org2blog
   :PROPERTIES:
   :ID:       org_gcr_2017-05-12_mara:B6246A7A-5514-4478-BC3D-7768B05B08B8
   :END:

Configure Org2blog for use, development, and support.

Sysop is likely to use this periodically.

Start EMACS with this command:

#+BEGIN_EXAMPLE
emacs --debug-init --no-init-file --no-splash --background-color white --foreground-color black --vertical-scroll-bars --eval '(switch-to-buffer "*Messages*")' --name O2B-TEST --title O2B-TEST --load ~/src/help/.org-mode-org2blog.emacs.el
#+END_EXAMPLE

#+NAME: org_gcr_2017-05-12_mara_AD27B44D-A88A-421F-9418-EE1B9E1977D5
#+BEGIN_SRC emacs-lisp
(load-file "~/src/help/.org-mode-fundamentals.emacs.el")
#+END_SRC

** Watch What You Eat
  :PROPERTIES:
  :ID:       org_gcr_2017-05-12_mara:BD133C8B-8DFF-45C0-967D-CB83693C54B4
  :END:

*Code requiring package-management can only follow this block.*

Before ELPA, I used SVN to manage software packages for EMACS. After ELPA,
I used ELPA-packages. Now this system uses MELPA and GNU. MELPA packages always
have their issues fixed very quickly. GNU packages rarely have issues.

Initialize Package.

#+NAME: org_gcr_2017-05-12_mara_0F6BBBBA-259E-46FC-AD7F-C954149CCCEA
#+BEGIN_SRC emacs-lisp
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives
             '("gnu" . "http://elpa.gnu.org/packages/") t)
#+END_SRC

Use-Package is the most configurable and performant way to manage ELPA packages.

Add the Use-Package distribution the load path.

#+NAME: org_gcr_2017-05-12_mara_867E1E1D-48E5-47C7-9B39-FD29F137665D
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path"~/src/use-package")
#+END_SRC

Load Use-Package and it's partner Diminish. Every package loaded before this
point uses ~require~. Every package loaded after this point uses ~use-package~.

#+NAME: org_gcr_2017-05-12_mara_3982F502-880C-4DF4-A1DF-07DA3EAA7D78
#+BEGIN_SRC emacs-lisp
(eval-when-compile
  (require 'use-package))
(use-package diminish)
#+END_SRC

** Blog
   :PROPERTIES:
   :ID:       org_gcr_2017-05-12_mara:AC5A3F2F-BF02-44D2-9EE1-BC6D6D8A7A00
   :END:

#+BEGIN_QUOTE
An elisp implementation of clientside XML-RPC
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_3989AFAA-23E6-4463-98E8-90F7ED269C1B
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/xml-rpc-el")
(require 'xml-rpc)

#+END_SRC

#+BEGIN_QUOTE
Weblog maintenance via XML-RPC APIs
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_C057BFE2-7242-495D-BCD2-62C6389A6551
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/metaweblog")
(require 'metaweblog)
#+END_SRC

#+BEGIN_QUOTE
Blog from Org mode to wordpress
#+END_QUOTE

#+NAME: org_gcr_2017-05-12_mara_EF1B02DF-BDB7-44AA-A018-B0BE6DA1C08F
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/org2blog")
(require 'org2blog)
(add-hook 'org-mode-hook #'org2blog/wp-org-mode-hook-fn)
#+END_SRC

Org2Blog depends on Org-Mode. This system loads Org-Mode from Git. Enter the
=ELPA= cache directory and delete it.

This system works with WisdomAndWonder. It keeps its posts separate giving focus
to each Web.

#+NAME: org_gcr_2017-05-12_mara_FF96F4B6-42B9-45D6-BEE6-6CDC9D6815AE
#+BEGIN_SRC emacs-lisp
(setq org2blog/wp-track-posts nil)
#+END_SRC

Configure Org2Blog.

#+NAME: org_gcr_2017-05-12_mara_854DE6E9-2208-42EB-A164-EC06E489B6B7
#+BEGIN_SRC emacs-lisp
(setq org2blog/wp-blog-alist
      '(("wisdomandwonder"
         :url "https://www.wisdomandwonder.com/xmlrpc.php"
         :username "admin"
         :default-categories ("Article" "Link")
         :confirm t
         :show 'show)))
#+END_SRC

* Pretty Mode
:PROPERTIES:
:ID:       org_gcr_2017-05-15_mara:CB452410-955E-4A91-A811-10755A35A142
:END:

Visualize ASCII values as their most likely Unicode representation.

#+NAME: org_gcr_2017-05-15_mara_5CF1DF19-27F5-4509-8E17-9CA0D1B29314
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/src/pretty-mode")
(require 'pretty-mode)
(global-pretty-mode t)
#+END_SRC
